# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lisagui.ui'
#
# Created: Sat Jan 15 15:34:02 2011
#      by: PyQt4 UI code generator 4.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_frmMain(object):
    def setupUi(self, frmMain):
        frmMain.setObjectName(_fromUtf8("frmMain"))
        frmMain.setEnabled(True)
        frmMain.resize(1000, 614)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frmMain.sizePolicy().hasHeightForWidth())
        frmMain.setSizePolicy(sizePolicy)
        frmMain.setMinimumSize(QtCore.QSize(1000, 600))
        frmMain.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        frmMain.setFont(font)
        self.verticalLayout_5 = QtGui.QVBoxLayout(frmMain)
        self.verticalLayout_5.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.cmbAccount = QtGui.QComboBox(frmMain)
        self.cmbAccount.setObjectName(_fromUtf8("cmbAccount"))
        self.gridLayout_8.addWidget(self.cmbAccount, 0, 2, 1, 1)
        self.lblAccount = QtGui.QLabel(frmMain)
        self.lblAccount.setObjectName(_fromUtf8("lblAccount"))
        self.gridLayout_8.addWidget(self.lblAccount, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_8)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.grpFinance = QtGui.QGroupBox(frmMain)
        self.grpFinance.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.grpFinance.setFont(font)
        self.grpFinance.setObjectName(_fromUtf8("grpFinance"))
        self.gridLayoutWidget_4 = QtGui.QWidget(self.grpFinance)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 381, 181))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.gridLayoutWidget_4.setFont(font)
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.txtComment = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.txtComment.setEnabled(True)
        self.txtComment.setObjectName(_fromUtf8("txtComment"))
        self.gridLayout_4.addWidget(self.txtComment, 4, 1, 1, 1)
        self.cmbProduct = QtGui.QComboBox(self.gridLayoutWidget_4)
        self.cmbProduct.setObjectName(_fromUtf8("cmbProduct"))
        self.gridLayout_4.addWidget(self.cmbProduct, 1, 1, 1, 1)
        self.lblComment = QtGui.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.lblComment.setFont(font)
        self.lblComment.setObjectName(_fromUtf8("lblComment"))
        self.gridLayout_4.addWidget(self.lblComment, 4, 0, 1, 1)
        self.lblAmount = QtGui.QLabel(self.gridLayoutWidget_4)
        self.lblAmount.setObjectName(_fromUtf8("lblAmount"))
        self.gridLayout_4.addWidget(self.lblAmount, 3, 0, 1, 1)
        self.lblProduct = QtGui.QLabel(self.gridLayoutWidget_4)
        self.lblProduct.setObjectName(_fromUtf8("lblProduct"))
        self.gridLayout_4.addWidget(self.lblProduct, 1, 0, 1, 1)
        self.lblDate = QtGui.QLabel(self.gridLayoutWidget_4)
        self.lblDate.setObjectName(_fromUtf8("lblDate"))
        self.gridLayout_4.addWidget(self.lblDate, 0, 0, 1, 1)
        self.spnAmount = QtGui.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.spnAmount.setMaximum(999999.99)
        self.spnAmount.setProperty(_fromUtf8("value"), 0.0)
        self.spnAmount.setObjectName(_fromUtf8("spnAmount"))
        self.gridLayout_4.addWidget(self.spnAmount, 3, 1, 1, 1)
        self.dtDate = QtGui.QDateEdit(self.gridLayoutWidget_4)
        self.dtDate.setCalendarPopup(True)
        self.dtDate.setObjectName(_fromUtf8("dtDate"))
        self.gridLayout_4.addWidget(self.dtDate, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.grpFinance, 0, 0, 1, 1)
        self.grpDetails = QtGui.QGroupBox(frmMain)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.grpDetails.setFont(font)
        self.grpDetails.setObjectName(_fromUtf8("grpDetails"))
        self.tabDetails = QtGui.QTabWidget(self.grpDetails)
        self.tabDetails.setGeometry(QtCore.QRect(10, 20, 371, 181))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.tabDetails.setFont(font)
        self.tabDetails.setElideMode(QtCore.Qt.ElideNone)
        self.tabDetails.setUsesScrollButtons(True)
        self.tabDetails.setDocumentMode(True)
        self.tabDetails.setObjectName(_fromUtf8("tabDetails"))
        self.tabPageEmpty = QtGui.QWidget()
        self.tabPageEmpty.setObjectName(_fromUtf8("tabPageEmpty"))
        self.scrollArea_2 = QtGui.QScrollArea(self.tabPageEmpty)
        self.scrollArea_2.setGeometry(QtCore.QRect(0, 0, 371, 161))
        self.scrollArea_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget(self.scrollArea_2)
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 371, 161))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.tabDetails.addTab(self.tabPageEmpty, _fromUtf8(""))
        self.tabPageStocks = QtGui.QWidget()
        self.tabPageStocks.setObjectName(_fromUtf8("tabPageStocks"))
        self.gridLayoutWidget_5 = QtGui.QWidget(self.tabPageStocks)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 351, 151))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.cmbMarketCode = QtGui.QComboBox(self.gridLayoutWidget_5)
        self.cmbMarketCode.setObjectName(_fromUtf8("cmbMarketCode"))
        self.gridLayout_5.addWidget(self.cmbMarketCode, 0, 4, 1, 1)
        self.spnPrice = QtGui.QDoubleSpinBox(self.gridLayoutWidget_5)
        self.spnPrice.setMaximum(999999.99)
        self.spnPrice.setObjectName(_fromUtf8("spnPrice"))
        self.gridLayout_5.addWidget(self.spnPrice, 3, 4, 1, 1)
        self.spnQuantity = QtGui.QSpinBox(self.gridLayoutWidget_5)
        self.spnQuantity.setMaximum(999999)
        self.spnQuantity.setObjectName(_fromUtf8("spnQuantity"))
        self.gridLayout_5.addWidget(self.spnQuantity, 2, 4, 1, 1)
        self.lblMarketCode = QtGui.QLabel(self.gridLayoutWidget_5)
        self.lblMarketCode.setObjectName(_fromUtf8("lblMarketCode"))
        self.gridLayout_5.addWidget(self.lblMarketCode, 0, 0, 1, 1)
        self.lblStockName = QtGui.QLabel(self.gridLayoutWidget_5)
        self.lblStockName.setObjectName(_fromUtf8("lblStockName"))
        self.gridLayout_5.addWidget(self.lblStockName, 1, 0, 1, 1)
        self.lblQuantity = QtGui.QLabel(self.gridLayoutWidget_5)
        self.lblQuantity.setObjectName(_fromUtf8("lblQuantity"))
        self.gridLayout_5.addWidget(self.lblQuantity, 2, 0, 1, 1)
        self.lblPrice = QtGui.QLabel(self.gridLayoutWidget_5)
        self.lblPrice.setObjectName(_fromUtf8("lblPrice"))
        self.gridLayout_5.addWidget(self.lblPrice, 3, 0, 1, 1)
        self.cmbStockName = QtGui.QComboBox(self.gridLayoutWidget_5)
        self.cmbStockName.setObjectName(_fromUtf8("cmbStockName"))
        self.gridLayout_5.addWidget(self.cmbStockName, 1, 4, 1, 1)
        self.tabDetails.addTab(self.tabPageStocks, _fromUtf8(""))
        self.tabPagePlace = QtGui.QWidget()
        self.tabPagePlace.setObjectName(_fromUtf8("tabPagePlace"))
        self.gridLayoutWidget_6 = QtGui.QWidget(self.tabPagePlace)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 10, 361, 151))
        self.gridLayoutWidget_6.setObjectName(_fromUtf8("gridLayoutWidget_6"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.cmbTeamB = QtGui.QComboBox(self.gridLayoutWidget_6)
        self.cmbTeamB.setObjectName(_fromUtf8("cmbTeamB"))
        self.gridLayout_6.addWidget(self.cmbTeamB, 1, 1, 1, 1)
        self.cmbTeamA = QtGui.QComboBox(self.gridLayoutWidget_6)
        self.cmbTeamA.setObjectName(_fromUtf8("cmbTeamA"))
        self.gridLayout_6.addWidget(self.cmbTeamA, 0, 1, 1, 1)
        self.cmbChoice = QtGui.QComboBox(self.gridLayoutWidget_6)
        self.cmbChoice.setObjectName(_fromUtf8("cmbChoice"))
        self.gridLayout_6.addWidget(self.cmbChoice, 2, 1, 1, 1)
        self.dtDateMatch = QtGui.QDateTimeEdit(self.gridLayoutWidget_6)
        self.dtDateMatch.setCalendarPopup(True)
        self.dtDateMatch.setObjectName(_fromUtf8("dtDateMatch"))
        self.gridLayout_6.addWidget(self.dtDateMatch, 3, 1, 1, 1)
        self.lblTeamA = QtGui.QLabel(self.gridLayoutWidget_6)
        self.lblTeamA.setObjectName(_fromUtf8("lblTeamA"))
        self.gridLayout_6.addWidget(self.lblTeamA, 0, 0, 1, 1)
        self.lblTeamB = QtGui.QLabel(self.gridLayoutWidget_6)
        self.lblTeamB.setObjectName(_fromUtf8("lblTeamB"))
        self.gridLayout_6.addWidget(self.lblTeamB, 1, 0, 1, 1)
        self.lblChoice = QtGui.QLabel(self.gridLayoutWidget_6)
        self.lblChoice.setObjectName(_fromUtf8("lblChoice"))
        self.gridLayout_6.addWidget(self.lblChoice, 2, 0, 1, 1)
        self.lblDateMatch = QtGui.QLabel(self.gridLayoutWidget_6)
        self.lblDateMatch.setObjectName(_fromUtf8("lblDateMatch"))
        self.gridLayout_6.addWidget(self.lblDateMatch, 3, 0, 1, 1)
        self.tabDetails.addTab(self.tabPagePlace, _fromUtf8(""))
        self.tabPageCashin = QtGui.QWidget()
        self.tabPageCashin.setObjectName(_fromUtf8("tabPageCashin"))
        self.gridLayoutWidget_7 = QtGui.QWidget(self.tabPageCashin)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(10, 10, 361, 151))
        self.gridLayoutWidget_7.setObjectName(_fromUtf8("gridLayoutWidget_7"))
        self.gridLayout_7 = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.cmbTeamA2 = QtGui.QComboBox(self.gridLayoutWidget_7)
        self.cmbTeamA2.setObjectName(_fromUtf8("cmbTeamA2"))
        self.gridLayout_7.addWidget(self.cmbTeamA2, 0, 1, 1, 1)
        self.cmbTeamB2 = QtGui.QComboBox(self.gridLayoutWidget_7)
        self.cmbTeamB2.setObjectName(_fromUtf8("cmbTeamB2"))
        self.gridLayout_7.addWidget(self.cmbTeamB2, 1, 1, 1, 1)
        self.spnScoreA = QtGui.QSpinBox(self.gridLayoutWidget_7)
        self.spnScoreA.setObjectName(_fromUtf8("spnScoreA"))
        self.gridLayout_7.addWidget(self.spnScoreA, 2, 1, 1, 1)
        self.spnScoreB = QtGui.QSpinBox(self.gridLayoutWidget_7)
        self.spnScoreB.setObjectName(_fromUtf8("spnScoreB"))
        self.gridLayout_7.addWidget(self.spnScoreB, 3, 1, 1, 1)
        self.lblTeamA2 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.lblTeamA2.setObjectName(_fromUtf8("lblTeamA2"))
        self.gridLayout_7.addWidget(self.lblTeamA2, 0, 0, 1, 1)
        self.lblTeamB2 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.lblTeamB2.setObjectName(_fromUtf8("lblTeamB2"))
        self.gridLayout_7.addWidget(self.lblTeamB2, 1, 0, 1, 1)
        self.lblScoreA = QtGui.QLabel(self.gridLayoutWidget_7)
        self.lblScoreA.setObjectName(_fromUtf8("lblScoreA"))
        self.gridLayout_7.addWidget(self.lblScoreA, 2, 0, 1, 1)
        self.lblScoreB = QtGui.QLabel(self.gridLayoutWidget_7)
        self.lblScoreB.setObjectName(_fromUtf8("lblScoreB"))
        self.gridLayout_7.addWidget(self.lblScoreB, 3, 0, 1, 1)
        self.tabDetails.addTab(self.tabPageCashin, _fromUtf8(""))
        self.gridLayout.addWidget(self.grpDetails, 0, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.btnClear = QtGui.QPushButton(frmMain)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.btnClear.setFont(font)
        self.btnClear.setObjectName(_fromUtf8("btnClear"))
        self.gridLayout_11.addWidget(self.btnClear, 0, 2, 1, 1)
        self.btnAdd = QtGui.QPushButton(frmMain)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.btnAdd.setFont(font)
        self.btnAdd.setObjectName(_fromUtf8("btnAdd"))
        self.gridLayout_11.addWidget(self.btnAdd, 0, 0, 1, 1)
        self.btnNewAccount = QtGui.QPushButton(frmMain)
        self.btnNewAccount.setObjectName(_fromUtf8("btnNewAccount"))
        self.gridLayout_11.addWidget(self.btnNewAccount, 0, 8, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem1, 0, 3, 1, 1)
        self.btnNewMarketCode = QtGui.QPushButton(frmMain)
        self.btnNewMarketCode.setObjectName(_fromUtf8("btnNewMarketCode"))
        self.gridLayout_11.addWidget(self.btnNewMarketCode, 0, 7, 1, 1)
        self.btnNewStock = QtGui.QPushButton(frmMain)
        self.btnNewStock.setObjectName(_fromUtf8("btnNewStock"))
        self.gridLayout_11.addWidget(self.btnNewStock, 0, 6, 1, 1)
        self.btnNew = QtGui.QPushButton(frmMain)
        self.btnNew.setObjectName(_fromUtf8("btnNew"))
        self.gridLayout_11.addWidget(self.btnNew, 0, 5, 1, 1)
        self.btnNewTeam = QtGui.QPushButton(frmMain)
        self.btnNewTeam.setObjectName(_fromUtf8("btnNewTeam"))
        self.gridLayout_11.addWidget(self.btnNewTeam, 0, 4, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_11)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblInfoFinance = QtGui.QLabel(frmMain)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.lblInfoFinance.setFont(font)
        self.lblInfoFinance.setObjectName(_fromUtf8("lblInfoFinance"))
        self.horizontalLayout.addWidget(self.lblInfoFinance)
        self.lblInfoDetails = QtGui.QLabel(frmMain)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.lblInfoDetails.setFont(font)
        self.lblInfoDetails.setObjectName(_fromUtf8("lblInfoDetails"))
        self.horizontalLayout.addWidget(self.lblInfoDetails)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.grpSummary = QtGui.QGroupBox(frmMain)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.grpSummary.setFont(font)
        self.grpSummary.setObjectName(_fromUtf8("grpSummary"))
        self.txtSummary = QtGui.QTextEdit(self.grpSummary)
        self.txtSummary.setGeometry(QtCore.QRect(10, 20, 961, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.txtSummary.setFont(font)
        self.txtSummary.setAutoFillBackground(False)
        self.txtSummary.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.txtSummary.setFrameShape(QtGui.QFrame.NoFrame)
        self.txtSummary.setFrameShadow(QtGui.QFrame.Sunken)
        self.txtSummary.setReadOnly(True)
        self.txtSummary.setObjectName(_fromUtf8("txtSummary"))
        self.gridLayout_3.addWidget(self.grpSummary, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.grpLastAdded_2 = QtGui.QGroupBox(frmMain)
        self.grpLastAdded_2.setObjectName(_fromUtf8("grpLastAdded_2"))
        self.txtLastAdded = QtGui.QTextEdit(self.grpLastAdded_2)
        self.txtLastAdded.setGeometry(QtCore.QRect(10, 20, 951, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.txtLastAdded.setFont(font)
        self.txtLastAdded.setAutoFillBackground(False)
        self.txtLastAdded.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.txtLastAdded.setFrameShape(QtGui.QFrame.NoFrame)
        self.txtLastAdded.setFrameShadow(QtGui.QFrame.Sunken)
        self.txtLastAdded.setReadOnly(True)
        self.txtLastAdded.setObjectName(_fromUtf8("txtLastAdded"))
        self.verticalLayout_4.addWidget(self.grpLastAdded_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.btnExit = QtGui.QPushButton(frmMain)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.btnExit.setFont(font)
        self.btnExit.setObjectName(_fromUtf8("btnExit"))
        self.gridLayout_2.addWidget(self.btnExit, 0, 4, 1, 1)
        self.btnExecute = QtGui.QPushButton(frmMain)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.btnExecute.setFont(font)
        self.btnExecute.setObjectName(_fromUtf8("btnExecute"))
        self.gridLayout_2.addWidget(self.btnExecute, 0, 1, 1, 1)
        self.btnAchievements = QtGui.QPushButton(frmMain)
        self.btnAchievements.setObjectName(_fromUtf8("btnAchievements"))
        self.gridLayout_2.addWidget(self.btnAchievements, 0, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.verticalLayout_3.setStretch(1, 2)
        self.verticalLayout_3.setStretch(4, 1)
        self.verticalLayout_3.setStretch(5, 1)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)

        self.retranslateUi(frmMain)
        self.tabDetails.setCurrentIndex(1)
        self.cmbTeamB.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(frmMain)

    def retranslateUi(self, frmMain):
        frmMain.setWindowTitle(QtGui.QApplication.translate("frmMain", "LISA", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAccount.setText(QtGui.QApplication.translate("frmMain", "Account", None, QtGui.QApplication.UnicodeUTF8))
        self.grpFinance.setTitle(QtGui.QApplication.translate("frmMain", "Finance", None, QtGui.QApplication.UnicodeUTF8))
        self.lblComment.setText(QtGui.QApplication.translate("frmMain", "Comment", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAmount.setText(QtGui.QApplication.translate("frmMain", "Amount", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProduct.setText(QtGui.QApplication.translate("frmMain", "Product", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDate.setText(QtGui.QApplication.translate("frmMain", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.dtDate.setDisplayFormat(QtGui.QApplication.translate("frmMain", "yyyy-MM-dd", None, QtGui.QApplication.UnicodeUTF8))
        self.grpDetails.setTitle(QtGui.QApplication.translate("frmMain", "Details", None, QtGui.QApplication.UnicodeUTF8))
        self.tabDetails.setTabText(self.tabDetails.indexOf(self.tabPageEmpty), QtGui.QApplication.translate("frmMain", "~/", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMarketCode.setText(QtGui.QApplication.translate("frmMain", "Market code", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStockName.setText(QtGui.QApplication.translate("frmMain", "Stock name", None, QtGui.QApplication.UnicodeUTF8))
        self.lblQuantity.setText(QtGui.QApplication.translate("frmMain", "Quantity", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPrice.setText(QtGui.QApplication.translate("frmMain", "Price", None, QtGui.QApplication.UnicodeUTF8))
        self.tabDetails.setTabText(self.tabDetails.indexOf(self.tabPageStocks), QtGui.QApplication.translate("frmMain", "Stocks", None, QtGui.QApplication.UnicodeUTF8))
        self.dtDateMatch.setDisplayFormat(QtGui.QApplication.translate("frmMain", "yyyy-MM-dd HH:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTeamA.setText(QtGui.QApplication.translate("frmMain", "Team A", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTeamB.setText(QtGui.QApplication.translate("frmMain", "Team B", None, QtGui.QApplication.UnicodeUTF8))
        self.lblChoice.setText(QtGui.QApplication.translate("frmMain", "Choice", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDateMatch.setText(QtGui.QApplication.translate("frmMain", "Date match", None, QtGui.QApplication.UnicodeUTF8))
        self.tabDetails.setTabText(self.tabDetails.indexOf(self.tabPagePlace), QtGui.QApplication.translate("frmMain", "Bets/Place", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTeamA2.setText(QtGui.QApplication.translate("frmMain", "Team A", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTeamB2.setText(QtGui.QApplication.translate("frmMain", "Team B", None, QtGui.QApplication.UnicodeUTF8))
        self.lblScoreA.setText(QtGui.QApplication.translate("frmMain", "Score A", None, QtGui.QApplication.UnicodeUTF8))
        self.lblScoreB.setText(QtGui.QApplication.translate("frmMain", "Score B", None, QtGui.QApplication.UnicodeUTF8))
        self.tabDetails.setTabText(self.tabDetails.indexOf(self.tabPageCashin), QtGui.QApplication.translate("frmMain", "Bets/Cashin", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClear.setText(QtGui.QApplication.translate("frmMain", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAdd.setText(QtGui.QApplication.translate("frmMain", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNewAccount.setText(QtGui.QApplication.translate("frmMain", "New Account", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNewMarketCode.setText(QtGui.QApplication.translate("frmMain", "New Market Code", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNewStock.setText(QtGui.QApplication.translate("frmMain", "New Stock", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNew.setText(QtGui.QApplication.translate("frmMain", "New Product", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNewTeam.setText(QtGui.QApplication.translate("frmMain", "New Team", None, QtGui.QApplication.UnicodeUTF8))
        self.lblInfoFinance.setText(QtGui.QApplication.translate("frmMain", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.lblInfoDetails.setText(QtGui.QApplication.translate("frmMain", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.grpSummary.setTitle(QtGui.QApplication.translate("frmMain", "Summary", None, QtGui.QApplication.UnicodeUTF8))
        self.grpLastAdded_2.setTitle(QtGui.QApplication.translate("frmMain", "Last Added", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExit.setText(QtGui.QApplication.translate("frmMain", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExecute.setText(QtGui.QApplication.translate("frmMain", "Execute", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAchievements.setText(QtGui.QApplication.translate("frmMain", "Achievements", None, QtGui.QApplication.UnicodeUTF8))

