# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lisagui.ui'
#
# Created: Wed Sep  1 20:15:42 2010
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_frmMain(object):
    def setupUi(self, frmMain):
        frmMain.setObjectName("frmMain")
        frmMain.resize(811, 546)
        self.gridLayoutWidget = QtGui.QWidget(frmMain)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 811, 221))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.grpFinance = QtGui.QGroupBox(self.gridLayoutWidget)
        self.grpFinance.setObjectName("grpFinance")
        self.gridLayoutWidget_4 = QtGui.QWidget(self.grpFinance)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 381, 181))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.txtComment = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.txtComment.setEnabled(True)
        self.txtComment.setObjectName("txtComment")
        self.gridLayout_4.addWidget(self.txtComment, 4, 1, 1, 1)
        self.cmbProduct = QtGui.QComboBox(self.gridLayoutWidget_4)
        self.cmbProduct.setObjectName("cmbProduct")
        self.gridLayout_4.addWidget(self.cmbProduct, 1, 1, 1, 1)
        self.cmbAccount = QtGui.QComboBox(self.gridLayoutWidget_4)
        self.cmbAccount.setObjectName("cmbAccount")
        self.gridLayout_4.addWidget(self.cmbAccount, 2, 1, 1, 1)
        self.lblComment = QtGui.QLabel(self.gridLayoutWidget_4)
        self.lblComment.setObjectName("lblComment")
        self.gridLayout_4.addWidget(self.lblComment, 4, 0, 1, 1)
        self.btnNew = QtGui.QPushButton(self.gridLayoutWidget_4)
        self.btnNew.setObjectName("btnNew")
        self.gridLayout_4.addWidget(self.btnNew, 1, 2, 1, 1)
        self.lblAmount = QtGui.QLabel(self.gridLayoutWidget_4)
        self.lblAmount.setObjectName("lblAmount")
        self.gridLayout_4.addWidget(self.lblAmount, 3, 0, 1, 1)
        self.lblAccount = QtGui.QLabel(self.gridLayoutWidget_4)
        self.lblAccount.setObjectName("lblAccount")
        self.gridLayout_4.addWidget(self.lblAccount, 2, 0, 1, 1)
        self.lblProduct = QtGui.QLabel(self.gridLayoutWidget_4)
        self.lblProduct.setObjectName("lblProduct")
        self.gridLayout_4.addWidget(self.lblProduct, 1, 0, 1, 1)
        self.lblDate = QtGui.QLabel(self.gridLayoutWidget_4)
        self.lblDate.setObjectName("lblDate")
        self.gridLayout_4.addWidget(self.lblDate, 0, 0, 1, 1)
        self.spnAmount = QtGui.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.spnAmount.setObjectName("spnAmount")
        self.gridLayout_4.addWidget(self.spnAmount, 3, 1, 1, 1)
        self.btnNewAccount = QtGui.QPushButton(self.gridLayoutWidget_4)
        self.btnNewAccount.setObjectName("btnNewAccount")
        self.gridLayout_4.addWidget(self.btnNewAccount, 2, 2, 1, 1)
        self.dtDate = QtGui.QDateEdit(self.gridLayoutWidget_4)
        self.dtDate.setCalendarPopup(True)
        self.dtDate.setObjectName("dtDate")
        self.gridLayout_4.addWidget(self.dtDate, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.grpFinance, 0, 0, 1, 1)
        self.grpDetails = QtGui.QGroupBox(self.gridLayoutWidget)
        self.grpDetails.setObjectName("grpDetails")
        self.tabDetails = QtGui.QTabWidget(self.grpDetails)
        self.tabDetails.setGeometry(QtCore.QRect(10, 20, 381, 191))
        self.tabDetails.setElideMode(QtCore.Qt.ElideNone)
        self.tabDetails.setUsesScrollButtons(True)
        self.tabDetails.setObjectName("tabDetails")
        self.tabPageEmpty = QtGui.QWidget()
        self.tabPageEmpty.setObjectName("tabPageEmpty")
        self.scrollArea_2 = QtGui.QScrollArea(self.tabPageEmpty)
        self.scrollArea_2.setGeometry(QtCore.QRect(0, 0, 371, 161))
        self.scrollArea_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtGui.QWidget(self.scrollArea_2)
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 371, 161))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.tabDetails.addTab(self.tabPageEmpty, "")
        self.tabPageStocks = QtGui.QWidget()
        self.tabPageStocks.setObjectName("tabPageStocks")
        self.gridLayoutWidget_5 = QtGui.QWidget(self.tabPageStocks)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 351, 151))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.cmbMarketCode = QtGui.QComboBox(self.gridLayoutWidget_5)
        self.cmbMarketCode.setObjectName("cmbMarketCode")
        self.gridLayout_5.addWidget(self.cmbMarketCode, 0, 4, 1, 1)
        self.spnPrice = QtGui.QDoubleSpinBox(self.gridLayoutWidget_5)
        self.spnPrice.setObjectName("spnPrice")
        self.gridLayout_5.addWidget(self.spnPrice, 3, 4, 1, 1)
        self.spnQuantity = QtGui.QSpinBox(self.gridLayoutWidget_5)
        self.spnQuantity.setObjectName("spnQuantity")
        self.gridLayout_5.addWidget(self.spnQuantity, 2, 4, 1, 1)
        self.btnNewMarketCode = QtGui.QPushButton(self.gridLayoutWidget_5)
        self.btnNewMarketCode.setObjectName("btnNewMarketCode")
        self.gridLayout_5.addWidget(self.btnNewMarketCode, 0, 5, 1, 1)
        self.lblMarketCode = QtGui.QLabel(self.gridLayoutWidget_5)
        self.lblMarketCode.setObjectName("lblMarketCode")
        self.gridLayout_5.addWidget(self.lblMarketCode, 0, 0, 1, 1)
        self.lblStockName = QtGui.QLabel(self.gridLayoutWidget_5)
        self.lblStockName.setObjectName("lblStockName")
        self.gridLayout_5.addWidget(self.lblStockName, 1, 0, 1, 1)
        self.lblQuantity = QtGui.QLabel(self.gridLayoutWidget_5)
        self.lblQuantity.setObjectName("lblQuantity")
        self.gridLayout_5.addWidget(self.lblQuantity, 2, 0, 1, 1)
        self.lblPrice = QtGui.QLabel(self.gridLayoutWidget_5)
        self.lblPrice.setObjectName("lblPrice")
        self.gridLayout_5.addWidget(self.lblPrice, 3, 0, 1, 1)
        self.cmbStockName = QtGui.QComboBox(self.gridLayoutWidget_5)
        self.cmbStockName.setObjectName("cmbStockName")
        self.gridLayout_5.addWidget(self.cmbStockName, 1, 4, 1, 1)
        self.btnNewStock = QtGui.QPushButton(self.gridLayoutWidget_5)
        self.btnNewStock.setObjectName("btnNewStock")
        self.gridLayout_5.addWidget(self.btnNewStock, 1, 5, 1, 1)
        self.tabDetails.addTab(self.tabPageStocks, "")
        self.tabPagePlace = QtGui.QWidget()
        self.tabPagePlace.setObjectName("tabPagePlace")
        self.gridLayoutWidget_6 = QtGui.QWidget(self.tabPagePlace)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 10, 361, 151))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtGui.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.cmbTeamB = QtGui.QComboBox(self.gridLayoutWidget_6)
        self.cmbTeamB.setObjectName("cmbTeamB")
        self.gridLayout_6.addWidget(self.cmbTeamB, 1, 1, 1, 1)
        self.cmbTeamA = QtGui.QComboBox(self.gridLayoutWidget_6)
        self.cmbTeamA.setObjectName("cmbTeamA")
        self.gridLayout_6.addWidget(self.cmbTeamA, 0, 1, 1, 1)
        self.cmbChoice = QtGui.QComboBox(self.gridLayoutWidget_6)
        self.cmbChoice.setObjectName("cmbChoice")
        self.gridLayout_6.addWidget(self.cmbChoice, 2, 1, 1, 1)
        self.dtDateMatch = QtGui.QDateTimeEdit(self.gridLayoutWidget_6)
        self.dtDateMatch.setCalendarPopup(True)
        self.dtDateMatch.setObjectName("dtDateMatch")
        self.gridLayout_6.addWidget(self.dtDateMatch, 3, 1, 1, 1)
        self.lblTeamA = QtGui.QLabel(self.gridLayoutWidget_6)
        self.lblTeamA.setObjectName("lblTeamA")
        self.gridLayout_6.addWidget(self.lblTeamA, 0, 0, 1, 1)
        self.lblTeamB = QtGui.QLabel(self.gridLayoutWidget_6)
        self.lblTeamB.setObjectName("lblTeamB")
        self.gridLayout_6.addWidget(self.lblTeamB, 1, 0, 1, 1)
        self.lblChoice = QtGui.QLabel(self.gridLayoutWidget_6)
        self.lblChoice.setObjectName("lblChoice")
        self.gridLayout_6.addWidget(self.lblChoice, 2, 0, 1, 1)
        self.lblDateMatch = QtGui.QLabel(self.gridLayoutWidget_6)
        self.lblDateMatch.setObjectName("lblDateMatch")
        self.gridLayout_6.addWidget(self.lblDateMatch, 3, 0, 1, 1)
        self.btnNewTeam = QtGui.QPushButton(self.gridLayoutWidget_6)
        self.btnNewTeam.setObjectName("btnNewTeam")
        self.gridLayout_6.addWidget(self.btnNewTeam, 0, 2, 1, 1)
        self.tabDetails.addTab(self.tabPagePlace, "")
        self.tabPageCashin = QtGui.QWidget()
        self.tabPageCashin.setObjectName("tabPageCashin")
        self.gridLayoutWidget_7 = QtGui.QWidget(self.tabPageCashin)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(10, 10, 361, 151))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.cmbTeamA2 = QtGui.QComboBox(self.gridLayoutWidget_7)
        self.cmbTeamA2.setObjectName("cmbTeamA2")
        self.gridLayout_7.addWidget(self.cmbTeamA2, 0, 1, 1, 1)
        self.cmbTeamB2 = QtGui.QComboBox(self.gridLayoutWidget_7)
        self.cmbTeamB2.setObjectName("cmbTeamB2")
        self.gridLayout_7.addWidget(self.cmbTeamB2, 1, 1, 1, 1)
        self.spnScoreA = QtGui.QSpinBox(self.gridLayoutWidget_7)
        self.spnScoreA.setObjectName("spnScoreA")
        self.gridLayout_7.addWidget(self.spnScoreA, 2, 1, 1, 1)
        self.spnScoreB = QtGui.QSpinBox(self.gridLayoutWidget_7)
        self.spnScoreB.setObjectName("spnScoreB")
        self.gridLayout_7.addWidget(self.spnScoreB, 3, 1, 1, 1)
        self.lblTeamA2 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.lblTeamA2.setObjectName("lblTeamA2")
        self.gridLayout_7.addWidget(self.lblTeamA2, 0, 0, 1, 1)
        self.lblTeamB2 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.lblTeamB2.setObjectName("lblTeamB2")
        self.gridLayout_7.addWidget(self.lblTeamB2, 1, 0, 1, 1)
        self.lblScoreA = QtGui.QLabel(self.gridLayoutWidget_7)
        self.lblScoreA.setObjectName("lblScoreA")
        self.gridLayout_7.addWidget(self.lblScoreA, 2, 0, 1, 1)
        self.lblScoreB = QtGui.QLabel(self.gridLayoutWidget_7)
        self.lblScoreB.setObjectName("lblScoreB")
        self.gridLayout_7.addWidget(self.lblScoreB, 3, 0, 1, 1)
        self.btnNewTeam2 = QtGui.QPushButton(self.gridLayoutWidget_7)
        self.btnNewTeam2.setObjectName("btnNewTeam2")
        self.gridLayout_7.addWidget(self.btnNewTeam2, 0, 2, 1, 1)
        self.tabDetails.addTab(self.tabPageCashin, "")
        self.gridLayout.addWidget(self.grpDetails, 0, 1, 1, 1)
        self.gridLayoutWidget_2 = QtGui.QWidget(frmMain)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(30, 269, 751, 41))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        self.btnExit = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.btnExit.setObjectName("btnExit")
        self.gridLayout_2.addWidget(self.btnExit, 0, 4, 1, 1)
        self.btnAdd = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.btnAdd.setObjectName("btnAdd")
        self.gridLayout_2.addWidget(self.btnAdd, 0, 0, 1, 1)
        self.btnExecute = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.btnExecute.setObjectName("btnExecute")
        self.gridLayout_2.addWidget(self.btnExecute, 0, 1, 1, 1)
        self.gridLayoutWidget_3 = QtGui.QWidget(frmMain)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 320, 811, 221))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.grpSummary = QtGui.QGroupBox(self.gridLayoutWidget_3)
        self.grpSummary.setObjectName("grpSummary")
        self.txtSummary = QtGui.QTextEdit(self.grpSummary)
        self.txtSummary.setGeometry(QtCore.QRect(10, 20, 791, 181))
        font = QtGui.QFont()
        font.setFamily("Dina")
        self.txtSummary.setFont(font)
        self.txtSummary.setAutoFillBackground(False)
        self.txtSummary.setStyleSheet("None")
        self.txtSummary.setFrameShape(QtGui.QFrame.NoFrame)
        self.txtSummary.setFrameShadow(QtGui.QFrame.Sunken)
        self.txtSummary.setObjectName("txtSummary")
        self.gridLayout_3.addWidget(self.grpSummary, 0, 0, 1, 1)
        self.horizontalLayoutWidget = QtGui.QWidget(frmMain)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 229, 791, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblInfoFinance = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lblInfoFinance.setObjectName("lblInfoFinance")
        self.horizontalLayout.addWidget(self.lblInfoFinance)
        self.lblInfoDetails = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lblInfoDetails.setObjectName("lblInfoDetails")
        self.horizontalLayout.addWidget(self.lblInfoDetails)

        self.retranslateUi(frmMain)
        self.tabDetails.setCurrentIndex(2)
        self.cmbTeamB.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(frmMain)

    def retranslateUi(self, frmMain):
        frmMain.setWindowTitle(QtGui.QApplication.translate("frmMain", "LISA", None, QtGui.QApplication.UnicodeUTF8))
        self.grpFinance.setTitle(QtGui.QApplication.translate("frmMain", "Finance", None, QtGui.QApplication.UnicodeUTF8))
        self.lblComment.setText(QtGui.QApplication.translate("frmMain", "Comment", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNew.setText(QtGui.QApplication.translate("frmMain", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAmount.setText(QtGui.QApplication.translate("frmMain", "Amount", None, QtGui.QApplication.UnicodeUTF8))
        self.lblAccount.setText(QtGui.QApplication.translate("frmMain", "Account", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProduct.setText(QtGui.QApplication.translate("frmMain", "Product", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDate.setText(QtGui.QApplication.translate("frmMain", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNewAccount.setText(QtGui.QApplication.translate("frmMain", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.dtDate.setDisplayFormat(QtGui.QApplication.translate("frmMain", "yyyy-MM-dd", None, QtGui.QApplication.UnicodeUTF8))
        self.grpDetails.setTitle(QtGui.QApplication.translate("frmMain", "Details", None, QtGui.QApplication.UnicodeUTF8))
        self.tabDetails.setTabText(self.tabDetails.indexOf(self.tabPageEmpty), QtGui.QApplication.translate("frmMain", "~/", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNewMarketCode.setText(QtGui.QApplication.translate("frmMain", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMarketCode.setText(QtGui.QApplication.translate("frmMain", "Market code", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStockName.setText(QtGui.QApplication.translate("frmMain", "Stock name", None, QtGui.QApplication.UnicodeUTF8))
        self.lblQuantity.setText(QtGui.QApplication.translate("frmMain", "Quantity", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPrice.setText(QtGui.QApplication.translate("frmMain", "Price", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNewStock.setText(QtGui.QApplication.translate("frmMain", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.tabDetails.setTabText(self.tabDetails.indexOf(self.tabPageStocks), QtGui.QApplication.translate("frmMain", "Stocks", None, QtGui.QApplication.UnicodeUTF8))
        self.dtDateMatch.setDisplayFormat(QtGui.QApplication.translate("frmMain", "yyyy-MM-dd HH:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTeamA.setText(QtGui.QApplication.translate("frmMain", "Team A", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTeamB.setText(QtGui.QApplication.translate("frmMain", "Team B", None, QtGui.QApplication.UnicodeUTF8))
        self.lblChoice.setText(QtGui.QApplication.translate("frmMain", "Choice", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDateMatch.setText(QtGui.QApplication.translate("frmMain", "Date match", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNewTeam.setText(QtGui.QApplication.translate("frmMain", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.tabDetails.setTabText(self.tabDetails.indexOf(self.tabPagePlace), QtGui.QApplication.translate("frmMain", "Bets/Place", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTeamA2.setText(QtGui.QApplication.translate("frmMain", "Team A", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTeamB2.setText(QtGui.QApplication.translate("frmMain", "Team B", None, QtGui.QApplication.UnicodeUTF8))
        self.lblScoreA.setText(QtGui.QApplication.translate("frmMain", "Score A", None, QtGui.QApplication.UnicodeUTF8))
        self.lblScoreB.setText(QtGui.QApplication.translate("frmMain", "Score B", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNewTeam2.setText(QtGui.QApplication.translate("frmMain", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.tabDetails.setTabText(self.tabDetails.indexOf(self.tabPageCashin), QtGui.QApplication.translate("frmMain", "Bets/Cashin", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExit.setText(QtGui.QApplication.translate("frmMain", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAdd.setText(QtGui.QApplication.translate("frmMain", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExecute.setText(QtGui.QApplication.translate("frmMain", "Execute", None, QtGui.QApplication.UnicodeUTF8))
        self.grpSummary.setTitle(QtGui.QApplication.translate("frmMain", "Summary", None, QtGui.QApplication.UnicodeUTF8))
        self.lblInfoFinance.setText(QtGui.QApplication.translate("frmMain", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.lblInfoDetails.setText(QtGui.QApplication.translate("frmMain", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))

