# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lisagui.ui'
#
# Created: Mon Feb 14 22:13:53 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_frm_main(object):
    def setupUi(self, frm_main):
        frm_main.setObjectName(_fromUtf8("frm_main"))
        frm_main.setEnabled(True)
        frm_main.resize(1000, 614)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frm_main.sizePolicy().hasHeightForWidth())
        frm_main.setSizePolicy(sizePolicy)
        frm_main.setMinimumSize(QtCore.QSize(1000, 600))
        frm_main.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        frm_main.setFont(font)
        self.verticalLayout_5 = QtGui.QVBoxLayout(frm_main)
        self.verticalLayout_5.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.cmb_account = QtGui.QComboBox(frm_main)
        self.cmb_account.setObjectName(_fromUtf8("cmb_account"))
        self.gridLayout_8.addWidget(self.cmb_account, 0, 2, 1, 1)
        self.lbl_account = QtGui.QLabel(frm_main)
        self.lbl_account.setObjectName(_fromUtf8("lbl_account"))
        self.gridLayout_8.addWidget(self.lbl_account, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_8)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.grp_finance = QtGui.QGroupBox(frm_main)
        self.grp_finance.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.grp_finance.setFont(font)
        self.grp_finance.setObjectName(_fromUtf8("grp_finance"))
        self.gridLayoutWidget_4 = QtGui.QWidget(self.grp_finance)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 381, 181))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.gridLayoutWidget_4.setFont(font)
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.txt_comment = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.txt_comment.setEnabled(True)
        self.txt_comment.setObjectName(_fromUtf8("txt_comment"))
        self.gridLayout_4.addWidget(self.txt_comment, 4, 1, 1, 1)
        self.cmb_product = QtGui.QComboBox(self.gridLayoutWidget_4)
        self.cmb_product.setObjectName(_fromUtf8("cmb_product"))
        self.gridLayout_4.addWidget(self.cmb_product, 1, 1, 1, 1)
        self.lbl_comment = QtGui.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.lbl_comment.setFont(font)
        self.lbl_comment.setObjectName(_fromUtf8("lbl_comment"))
        self.gridLayout_4.addWidget(self.lbl_comment, 4, 0, 1, 1)
        self.lbl_amount = QtGui.QLabel(self.gridLayoutWidget_4)
        self.lbl_amount.setObjectName(_fromUtf8("lbl_amount"))
        self.gridLayout_4.addWidget(self.lbl_amount, 3, 0, 1, 1)
        self.lbl_product = QtGui.QLabel(self.gridLayoutWidget_4)
        self.lbl_product.setObjectName(_fromUtf8("lbl_product"))
        self.gridLayout_4.addWidget(self.lbl_product, 1, 0, 1, 1)
        self.lbl_date = QtGui.QLabel(self.gridLayoutWidget_4)
        self.lbl_date.setObjectName(_fromUtf8("lbl_date"))
        self.gridLayout_4.addWidget(self.lbl_date, 0, 0, 1, 1)
        self.spn_amount = QtGui.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.spn_amount.setMaximum(999999.99)
        self.spn_amount.setProperty(_fromUtf8("value"), 0.0)
        self.spn_amount.setObjectName(_fromUtf8("spn_amount"))
        self.gridLayout_4.addWidget(self.spn_amount, 3, 1, 1, 1)
        self.dt_date = QtGui.QDateEdit(self.gridLayoutWidget_4)
        self.dt_date.setCalendarPopup(True)
        self.dt_date.setObjectName(_fromUtf8("dt_date"))
        self.gridLayout_4.addWidget(self.dt_date, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.grp_finance, 0, 0, 1, 1)
        self.grp_details = QtGui.QGroupBox(frm_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.grp_details.setFont(font)
        self.grp_details.setObjectName(_fromUtf8("grp_details"))
        self.tab_details = QtGui.QTabWidget(self.grp_details)
        self.tab_details.setGeometry(QtCore.QRect(10, 20, 381, 191))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.tab_details.setFont(font)
        self.tab_details.setTabPosition(QtGui.QTabWidget.North)
        self.tab_details.setTabShape(QtGui.QTabWidget.Rounded)
        self.tab_details.setElideMode(QtCore.Qt.ElideNone)
        self.tab_details.setUsesScrollButtons(True)
        self.tab_details.setDocumentMode(True)
        self.tab_details.setObjectName(_fromUtf8("tab_details"))
        self.tab_page_empty = QtGui.QWidget()
        self.tab_page_empty.setObjectName(_fromUtf8("tab_page_empty"))
        self.tab_details.addTab(self.tab_page_empty, _fromUtf8(""))
        self.tab_page_stocks = QtGui.QWidget()
        self.tab_page_stocks.setObjectName(_fromUtf8("tab_page_stocks"))
        self.gridLayoutWidget_5 = QtGui.QWidget(self.tab_page_stocks)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 351, 151))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.cmb_marketcode = QtGui.QComboBox(self.gridLayoutWidget_5)
        self.cmb_marketcode.setObjectName(_fromUtf8("cmb_marketcode"))
        self.gridLayout_5.addWidget(self.cmb_marketcode, 0, 4, 1, 1)
        self.spn_price = QtGui.QDoubleSpinBox(self.gridLayoutWidget_5)
        self.spn_price.setMaximum(999999.99)
        self.spn_price.setObjectName(_fromUtf8("spn_price"))
        self.gridLayout_5.addWidget(self.spn_price, 3, 4, 1, 1)
        self.spn_quantity = QtGui.QSpinBox(self.gridLayoutWidget_5)
        self.spn_quantity.setMaximum(999999)
        self.spn_quantity.setObjectName(_fromUtf8("spn_quantity"))
        self.gridLayout_5.addWidget(self.spn_quantity, 2, 4, 1, 1)
        self.lbl_marketcode = QtGui.QLabel(self.gridLayoutWidget_5)
        self.lbl_marketcode.setObjectName(_fromUtf8("lbl_marketcode"))
        self.gridLayout_5.addWidget(self.lbl_marketcode, 0, 0, 1, 1)
        self.lbl_stockname = QtGui.QLabel(self.gridLayoutWidget_5)
        self.lbl_stockname.setObjectName(_fromUtf8("lbl_stockname"))
        self.gridLayout_5.addWidget(self.lbl_stockname, 1, 0, 1, 1)
        self.lbl_quantity = QtGui.QLabel(self.gridLayoutWidget_5)
        self.lbl_quantity.setObjectName(_fromUtf8("lbl_quantity"))
        self.gridLayout_5.addWidget(self.lbl_quantity, 2, 0, 1, 1)
        self.lbl_price = QtGui.QLabel(self.gridLayoutWidget_5)
        self.lbl_price.setObjectName(_fromUtf8("lbl_price"))
        self.gridLayout_5.addWidget(self.lbl_price, 3, 0, 1, 1)
        self.cmb_stockname = QtGui.QComboBox(self.gridLayoutWidget_5)
        self.cmb_stockname.setObjectName(_fromUtf8("cmb_stockname"))
        self.gridLayout_5.addWidget(self.cmb_stockname, 1, 4, 1, 1)
        self.tab_details.addTab(self.tab_page_stocks, _fromUtf8(""))
        self.tab_page_place = QtGui.QWidget()
        self.tab_page_place.setObjectName(_fromUtf8("tab_page_place"))
        self.gridLayoutWidget_6 = QtGui.QWidget(self.tab_page_place)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 10, 361, 151))
        self.gridLayoutWidget_6.setObjectName(_fromUtf8("gridLayoutWidget_6"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.cmb_teamb = QtGui.QComboBox(self.gridLayoutWidget_6)
        self.cmb_teamb.setObjectName(_fromUtf8("cmb_teamb"))
        self.gridLayout_6.addWidget(self.cmb_teamb, 1, 1, 1, 1)
        self.cmb_teama = QtGui.QComboBox(self.gridLayoutWidget_6)
        self.cmb_teama.setObjectName(_fromUtf8("cmb_teama"))
        self.gridLayout_6.addWidget(self.cmb_teama, 0, 1, 1, 1)
        self.cmb_choice = QtGui.QComboBox(self.gridLayoutWidget_6)
        self.cmb_choice.setObjectName(_fromUtf8("cmb_choice"))
        self.gridLayout_6.addWidget(self.cmb_choice, 2, 1, 1, 1)
        self.dt_datematch = QtGui.QDateTimeEdit(self.gridLayoutWidget_6)
        self.dt_datematch.setCalendarPopup(True)
        self.dt_datematch.setObjectName(_fromUtf8("dt_datematch"))
        self.gridLayout_6.addWidget(self.dt_datematch, 3, 1, 1, 1)
        self.lbl_teama = QtGui.QLabel(self.gridLayoutWidget_6)
        self.lbl_teama.setObjectName(_fromUtf8("lbl_teama"))
        self.gridLayout_6.addWidget(self.lbl_teama, 0, 0, 1, 1)
        self.lbl_teamb = QtGui.QLabel(self.gridLayoutWidget_6)
        self.lbl_teamb.setObjectName(_fromUtf8("lbl_teamb"))
        self.gridLayout_6.addWidget(self.lbl_teamb, 1, 0, 1, 1)
        self.lbl_choice = QtGui.QLabel(self.gridLayoutWidget_6)
        self.lbl_choice.setObjectName(_fromUtf8("lbl_choice"))
        self.gridLayout_6.addWidget(self.lbl_choice, 2, 0, 1, 1)
        self.lbl_datematch = QtGui.QLabel(self.gridLayoutWidget_6)
        self.lbl_datematch.setObjectName(_fromUtf8("lbl_datematch"))
        self.gridLayout_6.addWidget(self.lbl_datematch, 3, 0, 1, 1)
        self.tab_details.addTab(self.tab_page_place, _fromUtf8(""))
        self.tab_page_cashin = QtGui.QWidget()
        self.tab_page_cashin.setObjectName(_fromUtf8("tab_page_cashin"))
        self.gridLayoutWidget_7 = QtGui.QWidget(self.tab_page_cashin)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(10, 10, 361, 151))
        self.gridLayoutWidget_7.setObjectName(_fromUtf8("gridLayoutWidget_7"))
        self.gridLayout_7 = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.cmb_teama2 = QtGui.QComboBox(self.gridLayoutWidget_7)
        self.cmb_teama2.setObjectName(_fromUtf8("cmb_teama2"))
        self.gridLayout_7.addWidget(self.cmb_teama2, 0, 1, 1, 1)
        self.cmb_teamb2 = QtGui.QComboBox(self.gridLayoutWidget_7)
        self.cmb_teamb2.setObjectName(_fromUtf8("cmb_teamb2"))
        self.gridLayout_7.addWidget(self.cmb_teamb2, 1, 1, 1, 1)
        self.spn_scorea = QtGui.QSpinBox(self.gridLayoutWidget_7)
        self.spn_scorea.setObjectName(_fromUtf8("spn_scorea"))
        self.gridLayout_7.addWidget(self.spn_scorea, 2, 1, 1, 1)
        self.spn_scoreb = QtGui.QSpinBox(self.gridLayoutWidget_7)
        self.spn_scoreb.setObjectName(_fromUtf8("spn_scoreb"))
        self.gridLayout_7.addWidget(self.spn_scoreb, 3, 1, 1, 1)
        self.lbl_teama2 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.lbl_teama2.setObjectName(_fromUtf8("lbl_teama2"))
        self.gridLayout_7.addWidget(self.lbl_teama2, 0, 0, 1, 1)
        self.lbl_teamb2 = QtGui.QLabel(self.gridLayoutWidget_7)
        self.lbl_teamb2.setObjectName(_fromUtf8("lbl_teamb2"))
        self.gridLayout_7.addWidget(self.lbl_teamb2, 1, 0, 1, 1)
        self.lbl_scorea = QtGui.QLabel(self.gridLayoutWidget_7)
        self.lbl_scorea.setObjectName(_fromUtf8("lbl_scorea"))
        self.gridLayout_7.addWidget(self.lbl_scorea, 2, 0, 1, 1)
        self.lbl_scoreb = QtGui.QLabel(self.gridLayoutWidget_7)
        self.lbl_scoreb.setObjectName(_fromUtf8("lbl_scoreb"))
        self.gridLayout_7.addWidget(self.lbl_scoreb, 3, 0, 1, 1)
        self.tab_details.addTab(self.tab_page_cashin, _fromUtf8(""))
        self.gridLayout.addWidget(self.grp_details, 0, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.btn_clear = QtGui.QPushButton(frm_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.btn_clear.setFont(font)
        self.btn_clear.setObjectName(_fromUtf8("btn_clear"))
        self.gridLayout_11.addWidget(self.btn_clear, 0, 2, 1, 1)
        self.btn_add = QtGui.QPushButton(frm_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.btn_add.setFont(font)
        self.btn_add.setObjectName(_fromUtf8("btn_add"))
        self.gridLayout_11.addWidget(self.btn_add, 0, 0, 1, 1)
        self.btn_new_account = QtGui.QPushButton(frm_main)
        self.btn_new_account.setObjectName(_fromUtf8("btn_new_account"))
        self.gridLayout_11.addWidget(self.btn_new_account, 0, 8, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem1, 0, 3, 1, 1)
        self.btn_new_marketcode = QtGui.QPushButton(frm_main)
        self.btn_new_marketcode.setObjectName(_fromUtf8("btn_new_marketcode"))
        self.gridLayout_11.addWidget(self.btn_new_marketcode, 0, 7, 1, 1)
        self.btn_new_stock = QtGui.QPushButton(frm_main)
        self.btn_new_stock.setObjectName(_fromUtf8("btn_new_stock"))
        self.gridLayout_11.addWidget(self.btn_new_stock, 0, 6, 1, 1)
        self.btn_new_product = QtGui.QPushButton(frm_main)
        self.btn_new_product.setObjectName(_fromUtf8("btn_new_product"))
        self.gridLayout_11.addWidget(self.btn_new_product, 0, 5, 1, 1)
        self.btn_new_team = QtGui.QPushButton(frm_main)
        self.btn_new_team.setObjectName(_fromUtf8("btn_new_team"))
        self.gridLayout_11.addWidget(self.btn_new_team, 0, 4, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_11)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lbl_infofinance = QtGui.QLabel(frm_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.lbl_infofinance.setFont(font)
        self.lbl_infofinance.setObjectName(_fromUtf8("lbl_infofinance"))
        self.horizontalLayout.addWidget(self.lbl_infofinance)
        self.lbl_infodetails = QtGui.QLabel(frm_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.lbl_infodetails.setFont(font)
        self.lbl_infodetails.setObjectName(_fromUtf8("lbl_infodetails"))
        self.horizontalLayout.addWidget(self.lbl_infodetails)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.grp_summary = QtGui.QGroupBox(frm_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.grp_summary.setFont(font)
        self.grp_summary.setObjectName(_fromUtf8("grp_summary"))
        self.txt_summary = QtGui.QTextEdit(self.grp_summary)
        self.txt_summary.setGeometry(QtCore.QRect(10, 20, 961, 131))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.txt_summary.setFont(font)
        self.txt_summary.setAutoFillBackground(False)
        self.txt_summary.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.txt_summary.setFrameShape(QtGui.QFrame.NoFrame)
        self.txt_summary.setFrameShadow(QtGui.QFrame.Sunken)
        self.txt_summary.setReadOnly(True)
        self.txt_summary.setObjectName(_fromUtf8("txt_summary"))
        self.gridLayout_3.addWidget(self.grp_summary, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.btn_exit = QtGui.QPushButton(frm_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.btn_exit.setFont(font)
        self.btn_exit.setObjectName(_fromUtf8("btn_exit"))
        self.gridLayout_2.addWidget(self.btn_exit, 0, 3, 1, 1)
        self.btn_execute = QtGui.QPushButton(frm_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.btn_execute.setFont(font)
        self.btn_execute.setObjectName(_fromUtf8("btn_execute"))
        self.gridLayout_2.addWidget(self.btn_execute, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.verticalLayout_3.setStretch(1, 2)
        self.verticalLayout_3.setStretch(4, 1)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)

        self.retranslateUi(frm_main)
        self.tab_details.setCurrentIndex(0)
        self.cmb_teamb.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(frm_main)

    def retranslateUi(self, frm_main):
        frm_main.setWindowTitle(QtGui.QApplication.translate("frm_main", "LISA", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_account.setText(QtGui.QApplication.translate("frm_main", "Account", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_finance.setTitle(QtGui.QApplication.translate("frm_main", "Finance", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_comment.setText(QtGui.QApplication.translate("frm_main", "Comment", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_amount.setText(QtGui.QApplication.translate("frm_main", "Amount", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_product.setText(QtGui.QApplication.translate("frm_main", "Product", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_date.setText(QtGui.QApplication.translate("frm_main", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.dt_date.setDisplayFormat(QtGui.QApplication.translate("frm_main", "yyyy-MM-dd", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_details.setTitle(QtGui.QApplication.translate("frm_main", "Details", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_details.setTabText(self.tab_details.indexOf(self.tab_page_empty), QtGui.QApplication.translate("frm_main", "~/", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_marketcode.setText(QtGui.QApplication.translate("frm_main", "Market code", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_stockname.setText(QtGui.QApplication.translate("frm_main", "Stock name", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_quantity.setText(QtGui.QApplication.translate("frm_main", "Quantity", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_price.setText(QtGui.QApplication.translate("frm_main", "Price", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_details.setTabText(self.tab_details.indexOf(self.tab_page_stocks), QtGui.QApplication.translate("frm_main", "Stocks", None, QtGui.QApplication.UnicodeUTF8))
        self.dt_datematch.setDisplayFormat(QtGui.QApplication.translate("frm_main", "yyyy-MM-dd HH:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_teama.setText(QtGui.QApplication.translate("frm_main", "Team A", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_teamb.setText(QtGui.QApplication.translate("frm_main", "Team B", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_choice.setText(QtGui.QApplication.translate("frm_main", "Choice", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_datematch.setText(QtGui.QApplication.translate("frm_main", "Date match", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_details.setTabText(self.tab_details.indexOf(self.tab_page_place), QtGui.QApplication.translate("frm_main", "Bets/Place", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_teama2.setText(QtGui.QApplication.translate("frm_main", "Team A", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_teamb2.setText(QtGui.QApplication.translate("frm_main", "Team B", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_scorea.setText(QtGui.QApplication.translate("frm_main", "Score A", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_scoreb.setText(QtGui.QApplication.translate("frm_main", "Score B", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_details.setTabText(self.tab_details.indexOf(self.tab_page_cashin), QtGui.QApplication.translate("frm_main", "Bets/Cashin", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_clear.setText(QtGui.QApplication.translate("frm_main", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_add.setText(QtGui.QApplication.translate("frm_main", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_new_account.setText(QtGui.QApplication.translate("frm_main", "New Account", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_new_marketcode.setText(QtGui.QApplication.translate("frm_main", "New Market Code", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_new_stock.setText(QtGui.QApplication.translate("frm_main", "New Stock", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_new_product.setText(QtGui.QApplication.translate("frm_main", "New Product", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_new_team.setText(QtGui.QApplication.translate("frm_main", "New Team", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_infofinance.setText(QtGui.QApplication.translate("frm_main", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_infodetails.setText(QtGui.QApplication.translate("frm_main", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_summary.setTitle(QtGui.QApplication.translate("frm_main", "Summary", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_exit.setText(QtGui.QApplication.translate("frm_main", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_execute.setText(QtGui.QApplication.translate("frm_main", "Execute", None, QtGui.QApplication.UnicodeUTF8))

