# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lisa.ui'
#
# Created: Tue Mar 13 20:26:52 2012
#      by: PyQt4 UI code generator 4.9
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_frm_main(object):
    def setupUi(self, frm_main):
        frm_main.setObjectName(_fromUtf8("frm_main"))
        frm_main.setEnabled(True)
        frm_main.resize(1239, 615)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frm_main.sizePolicy().hasHeightForWidth())
        frm_main.setSizePolicy(sizePolicy)
        frm_main.setMinimumSize(QtCore.QSize(1200, 600))
        frm_main.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        frm_main.setFont(font)
        self.gridLayout = QtGui.QGridLayout(frm_main)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gl_main = QtGui.QGridLayout()
        self.gl_main.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gl_main.setMargin(1)
        self.gl_main.setVerticalSpacing(6)
        self.gl_main.setObjectName(_fromUtf8("gl_main"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.cmb_account = QtGui.QComboBox(frm_main)
        self.cmb_account.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.cmb_account.setEditable(True)
        self.cmb_account.setObjectName(_fromUtf8("cmb_account"))
        self.gridLayout_8.addWidget(self.cmb_account, 0, 5, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem, 0, 3, 1, 1)
        self.lbl_account = QtGui.QLabel(frm_main)
        self.lbl_account.setObjectName(_fromUtf8("lbl_account"))
        self.gridLayout_8.addWidget(self.lbl_account, 0, 4, 1, 1)
        self.lbl_infofinance = QtGui.QLabel(frm_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.lbl_infofinance.setFont(font)
        self.lbl_infofinance.setObjectName(_fromUtf8("lbl_infofinance"))
        self.gridLayout_8.addWidget(self.lbl_infofinance, 0, 0, 1, 1)
        self.gl_main.addLayout(self.gridLayout_8, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btn_add = QtGui.QPushButton(frm_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.btn_add.setFont(font)
        self.btn_add.setObjectName(_fromUtf8("btn_add"))
        self.horizontalLayout_2.addWidget(self.btn_add)
        self.btn_clear = QtGui.QPushButton(frm_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.btn_clear.setFont(font)
        self.btn_clear.setObjectName(_fromUtf8("btn_clear"))
        self.horizontalLayout_2.addWidget(self.btn_clear)
        self.btn_execute = QtGui.QPushButton(frm_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.btn_execute.setFont(font)
        self.btn_execute.setObjectName(_fromUtf8("btn_execute"))
        self.horizontalLayout_2.addWidget(self.btn_execute)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lbl_infodetails = QtGui.QLabel(frm_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.lbl_infodetails.setFont(font)
        self.lbl_infodetails.setObjectName(_fromUtf8("lbl_infodetails"))
        self.horizontalLayout_2.addWidget(self.lbl_infodetails)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btn_exit = QtGui.QPushButton(frm_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.btn_exit.setFont(font)
        self.btn_exit.setObjectName(_fromUtf8("btn_exit"))
        self.horizontalLayout_2.addWidget(self.btn_exit)
        self.gl_main.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setVerticalSpacing(2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.cmb_product = QtGui.QComboBox(frm_main)
        self.cmb_product.setMinimumSize(QtCore.QSize(150, 0))
        self.cmb_product.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.cmb_product.setEditable(True)
        self.cmb_product.setObjectName(_fromUtf8("cmb_product"))
        self.gridLayout_4.addWidget(self.cmb_product, 1, 3, 1, 1)
        self.spn_amount = QtGui.QDoubleSpinBox(frm_main)
        self.spn_amount.setMinimumSize(QtCore.QSize(10, 0))
        self.spn_amount.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.spn_amount.setMaximum(999999.99)
        self.spn_amount.setProperty("value", 0.0)
        self.spn_amount.setObjectName(_fromUtf8("spn_amount"))
        self.gridLayout_4.addWidget(self.spn_amount, 1, 7, 1, 1)
        self.cmb_object = QtGui.QComboBox(frm_main)
        self.cmb_object.setMinimumSize(QtCore.QSize(100, 0))
        self.cmb_object.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cmb_object.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.cmb_object.setEditable(True)
        self.cmb_object.setObjectName(_fromUtf8("cmb_object"))
        self.gridLayout_4.addWidget(self.cmb_object, 1, 5, 1, 1)
        self.lbl_stockname = QtGui.QLabel(frm_main)
        self.lbl_stockname.setObjectName(_fromUtf8("lbl_stockname"))
        self.gridLayout_4.addWidget(self.lbl_stockname, 0, 10, 1, 1)
        self.dt_date = QtGui.QDateEdit(frm_main)
        self.dt_date.setMinimumSize(QtCore.QSize(90, 0))
        self.dt_date.setCalendarPopup(True)
        self.dt_date.setObjectName(_fromUtf8("dt_date"))
        self.gridLayout_4.addWidget(self.dt_date, 1, 1, 1, 1)
        self.lbl_marketcode = QtGui.QLabel(frm_main)
        self.lbl_marketcode.setObjectName(_fromUtf8("lbl_marketcode"))
        self.gridLayout_4.addWidget(self.lbl_marketcode, 0, 9, 1, 1)
        self.lbl_product = QtGui.QLabel(frm_main)
        self.lbl_product.setObjectName(_fromUtf8("lbl_product"))
        self.gridLayout_4.addWidget(self.lbl_product, 0, 3, 1, 1)
        self.spn_price = QtGui.QDoubleSpinBox(frm_main)
        self.spn_price.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        self.spn_price.setFont(font)
        self.spn_price.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.spn_price.setMaximum(999999.99)
        self.spn_price.setObjectName(_fromUtf8("spn_price"))
        self.gridLayout_4.addWidget(self.spn_price, 1, 12, 1, 1)
        self.lbl_comment = QtGui.QLabel(frm_main)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.lbl_comment.setFont(font)
        self.lbl_comment.setObjectName(_fromUtf8("lbl_comment"))
        self.gridLayout_4.addWidget(self.lbl_comment, 0, 8, 1, 1)
        self.lbl_quantity = QtGui.QLabel(frm_main)
        self.lbl_quantity.setObjectName(_fromUtf8("lbl_quantity"))
        self.gridLayout_4.addWidget(self.lbl_quantity, 0, 11, 1, 1)
        self.lbl_amount = QtGui.QLabel(frm_main)
        self.lbl_amount.setObjectName(_fromUtf8("lbl_amount"))
        self.gridLayout_4.addWidget(self.lbl_amount, 0, 7, 1, 1)
        self.lbl_date = QtGui.QLabel(frm_main)
        self.lbl_date.setObjectName(_fromUtf8("lbl_date"))
        self.gridLayout_4.addWidget(self.lbl_date, 0, 1, 1, 1)
        self.lbl_commission = QtGui.QLabel(frm_main)
        self.lbl_commission.setObjectName(_fromUtf8("lbl_commission"))
        self.gridLayout_4.addWidget(self.lbl_commission, 0, 13, 1, 1)
        self.txt_stockdescription = QtGui.QLineEdit(frm_main)
        self.txt_stockdescription.setObjectName(_fromUtf8("txt_stockdescription"))
        self.gridLayout_4.addWidget(self.txt_stockdescription, 2, 10, 1, 1)
        self.cmb_marketcode = QtGui.QComboBox(frm_main)
        self.cmb_marketcode.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.cmb_marketcode.setEditable(True)
        self.cmb_marketcode.setObjectName(_fromUtf8("cmb_marketcode"))
        self.gridLayout_4.addWidget(self.cmb_marketcode, 1, 9, 1, 1)
        self.spn_quantity = QtGui.QSpinBox(frm_main)
        self.spn_quantity.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        self.spn_quantity.setFont(font)
        self.spn_quantity.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.spn_quantity.setMaximum(999999)
        self.spn_quantity.setObjectName(_fromUtf8("spn_quantity"))
        self.gridLayout_4.addWidget(self.spn_quantity, 1, 11, 1, 1)
        self.txt_marketdescription = QtGui.QLineEdit(frm_main)
        self.txt_marketdescription.setObjectName(_fromUtf8("txt_marketdescription"))
        self.gridLayout_4.addWidget(self.txt_marketdescription, 2, 9, 1, 1)
        self.lbl_price = QtGui.QLabel(frm_main)
        self.lbl_price.setObjectName(_fromUtf8("lbl_price"))
        self.gridLayout_4.addWidget(self.lbl_price, 0, 12, 1, 1)
        self.txt_comment = QtGui.QLineEdit(frm_main)
        self.txt_comment.setEnabled(True)
        self.txt_comment.setMinimumSize(QtCore.QSize(200, 0))
        self.txt_comment.setObjectName(_fromUtf8("txt_comment"))
        self.gridLayout_4.addWidget(self.txt_comment, 1, 8, 1, 1)
        self.lbl_object = QtGui.QLabel(frm_main)
        self.lbl_object.setObjectName(_fromUtf8("lbl_object"))
        self.gridLayout_4.addWidget(self.lbl_object, 0, 5, 1, 1)
        self.cmb_stockname = QtGui.QComboBox(frm_main)
        self.cmb_stockname.setMinimumSize(QtCore.QSize(150, 0))
        self.cmb_stockname.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.cmb_stockname.setEditable(True)
        self.cmb_stockname.setObjectName(_fromUtf8("cmb_stockname"))
        self.gridLayout_4.addWidget(self.cmb_stockname, 1, 10, 1, 1)
        self.spn_commission = QtGui.QDoubleSpinBox(frm_main)
        self.spn_commission.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        self.spn_commission.setFont(font)
        self.spn_commission.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.spn_commission.setMaximum(999999.99)
        self.spn_commission.setObjectName(_fromUtf8("spn_commission"))
        self.gridLayout_4.addWidget(self.spn_commission, 1, 13, 1, 1)
        self.lbl_tax = QtGui.QLabel(frm_main)
        self.lbl_tax.setObjectName(_fromUtf8("lbl_tax"))
        self.gridLayout_4.addWidget(self.lbl_tax, 0, 14, 1, 1)
        self.spn_tax = QtGui.QDoubleSpinBox(frm_main)
        self.spn_tax.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        self.spn_tax.setFont(font)
        self.spn_tax.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.spn_tax.setMaximum(999999.99)
        self.spn_tax.setObjectName(_fromUtf8("spn_tax"))
        self.gridLayout_4.addWidget(self.spn_tax, 1, 14, 1, 1)
        self.spn_risk = QtGui.QDoubleSpinBox(frm_main)
        self.spn_risk.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        self.spn_risk.setFont(font)
        self.spn_risk.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.spn_risk.setMaximum(999999.99)
        self.spn_risk.setObjectName(_fromUtf8("spn_risk"))
        self.gridLayout_4.addWidget(self.spn_risk, 1, 15, 1, 1)
        self.lbl_risk = QtGui.QLabel(frm_main)
        self.lbl_risk.setObjectName(_fromUtf8("lbl_risk"))
        self.gridLayout_4.addWidget(self.lbl_risk, 0, 15, 1, 1)
        self.gl_main.addLayout(self.gridLayout_4, 2, 0, 1, 1)
        self.vl_table = QtGui.QVBoxLayout()
        self.vl_table.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.vl_table.setObjectName(_fromUtf8("vl_table"))
        self.gl_main.addLayout(self.vl_table, 5, 0, 1, 1)
        self.gl_main.setRowMinimumHeight(5, 250)
        self.gl_main.setRowStretch(4, 10)
        self.gl_main.setRowStretch(5, 100)
        self.gridLayout.addLayout(self.gl_main, 0, 0, 1, 1)

        self.retranslateUi(frm_main)
        QtCore.QMetaObject.connectSlotsByName(frm_main)
        frm_main.setTabOrder(self.cmb_account, self.dt_date)
        frm_main.setTabOrder(self.dt_date, self.cmb_product)
        frm_main.setTabOrder(self.cmb_product, self.cmb_object)
        frm_main.setTabOrder(self.cmb_object, self.spn_amount)
        frm_main.setTabOrder(self.spn_amount, self.txt_comment)
        frm_main.setTabOrder(self.txt_comment, self.cmb_marketcode)
        frm_main.setTabOrder(self.cmb_marketcode, self.cmb_stockname)
        frm_main.setTabOrder(self.cmb_stockname, self.spn_quantity)
        frm_main.setTabOrder(self.spn_quantity, self.spn_price)
        frm_main.setTabOrder(self.spn_price, self.spn_commission)
        frm_main.setTabOrder(self.spn_commission, self.spn_tax)
        frm_main.setTabOrder(self.spn_tax, self.spn_risk)
        frm_main.setTabOrder(self.spn_risk, self.btn_add)
        frm_main.setTabOrder(self.btn_add, self.txt_marketdescription)
        frm_main.setTabOrder(self.txt_marketdescription, self.txt_stockdescription)
        frm_main.setTabOrder(self.txt_stockdescription, self.btn_clear)
        frm_main.setTabOrder(self.btn_clear, self.btn_execute)
        frm_main.setTabOrder(self.btn_execute, self.btn_exit)

    def retranslateUi(self, frm_main):
        frm_main.setWindowTitle(QtGui.QApplication.translate("frm_main", "LISA", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_account.setText(QtGui.QApplication.translate("frm_main", "Account", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_infofinance.setText(QtGui.QApplication.translate("frm_main", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_add.setText(QtGui.QApplication.translate("frm_main", "&Add", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_clear.setText(QtGui.QApplication.translate("frm_main", "&Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_execute.setText(QtGui.QApplication.translate("frm_main", "E&xecute", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_infodetails.setText(QtGui.QApplication.translate("frm_main", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_exit.setText(QtGui.QApplication.translate("frm_main", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_stockname.setText(QtGui.QApplication.translate("frm_main", "Stock name", None, QtGui.QApplication.UnicodeUTF8))
        self.dt_date.setDisplayFormat(QtGui.QApplication.translate("frm_main", "yyyy-MM-dd", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_marketcode.setText(QtGui.QApplication.translate("frm_main", "Market code", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_product.setText(QtGui.QApplication.translate("frm_main", "Product", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_comment.setText(QtGui.QApplication.translate("frm_main", "Comment", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_quantity.setText(QtGui.QApplication.translate("frm_main", "Quantity", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_amount.setText(QtGui.QApplication.translate("frm_main", "Amount", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_date.setText(QtGui.QApplication.translate("frm_main", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_commission.setText(QtGui.QApplication.translate("frm_main", "Commission", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_price.setText(QtGui.QApplication.translate("frm_main", "Price", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_object.setText(QtGui.QApplication.translate("frm_main", "Object", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_tax.setText(QtGui.QApplication.translate("frm_main", "Tax（％）", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_risk.setText(QtGui.QApplication.translate("frm_main", "Risk", None, QtGui.QApplication.UnicodeUTF8))

