# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewpyqt.ui'
#
# Created: Sun Mar  3 09:22:51 2013
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1198, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem, 0, 7, 1, 1)
        self.lbl_check = QtGui.QLabel(self.centralwidget)
        self.lbl_check.setFrameShape(QtGui.QFrame.Panel)
        self.lbl_check.setFrameShadow(QtGui.QFrame.Raised)
        self.lbl_check.setObjectName(_fromUtf8("lbl_check"))
        self.gridLayout_10.addWidget(self.lbl_check, 0, 5, 1, 1)
        self.cmb_account = QtGui.QComboBox(self.centralwidget)
        self.cmb_account.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.cmb_account.setEditable(True)
        self.cmb_account.setObjectName(_fromUtf8("cmb_account"))
        self.gridLayout_10.addWidget(self.cmb_account, 0, 3, 1, 1)
        self.lbl_infofinance = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.lbl_infofinance.setFont(font)
        self.lbl_infofinance.setObjectName(_fromUtf8("lbl_infofinance"))
        self.gridLayout_10.addWidget(self.lbl_infofinance, 0, 8, 1, 1)
        self.lbl_account = QtGui.QLabel(self.centralwidget)
        self.lbl_account.setObjectName(_fromUtf8("lbl_account"))
        self.gridLayout_10.addWidget(self.lbl_account, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem1, 0, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_10)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setHorizontalSpacing(3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lbl_date = QtGui.QLabel(self.centralwidget)
        self.lbl_date.setObjectName(_fromUtf8("lbl_date"))
        self.gridLayout.addWidget(self.lbl_date, 0, 0, 1, 1)
        self.lbl_category = QtGui.QLabel(self.centralwidget)
        self.lbl_category.setObjectName(_fromUtf8("lbl_category"))
        self.gridLayout.addWidget(self.lbl_category, 0, 1, 1, 1)
        self.lbl_subcategory = QtGui.QLabel(self.centralwidget)
        self.lbl_subcategory.setObjectName(_fromUtf8("lbl_subcategory"))
        self.gridLayout.addWidget(self.lbl_subcategory, 0, 2, 1, 1)
        self.lbl_amount = QtGui.QLabel(self.centralwidget)
        self.lbl_amount.setObjectName(_fromUtf8("lbl_amount"))
        self.gridLayout.addWidget(self.lbl_amount, 0, 3, 1, 1)
        self.lbl_comment = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.lbl_comment.setFont(font)
        self.lbl_comment.setObjectName(_fromUtf8("lbl_comment"))
        self.gridLayout.addWidget(self.lbl_comment, 0, 4, 1, 1)
        self.lbl_marketcode = QtGui.QLabel(self.centralwidget)
        self.lbl_marketcode.setObjectName(_fromUtf8("lbl_marketcode"))
        self.gridLayout.addWidget(self.lbl_marketcode, 0, 5, 1, 1)
        self.lbl_stockname = QtGui.QLabel(self.centralwidget)
        self.lbl_stockname.setObjectName(_fromUtf8("lbl_stockname"))
        self.gridLayout.addWidget(self.lbl_stockname, 0, 6, 1, 1)
        self.lbl_quantity = QtGui.QLabel(self.centralwidget)
        self.lbl_quantity.setObjectName(_fromUtf8("lbl_quantity"))
        self.gridLayout.addWidget(self.lbl_quantity, 0, 7, 1, 1)
        self.lbl_price = QtGui.QLabel(self.centralwidget)
        self.lbl_price.setObjectName(_fromUtf8("lbl_price"))
        self.gridLayout.addWidget(self.lbl_price, 0, 8, 1, 1)
        self.lbl_commission = QtGui.QLabel(self.centralwidget)
        self.lbl_commission.setObjectName(_fromUtf8("lbl_commission"))
        self.gridLayout.addWidget(self.lbl_commission, 0, 9, 1, 1)
        self.lbl_tax = QtGui.QLabel(self.centralwidget)
        self.lbl_tax.setObjectName(_fromUtf8("lbl_tax"))
        self.gridLayout.addWidget(self.lbl_tax, 0, 10, 1, 1)
        self.lbl_risk = QtGui.QLabel(self.centralwidget)
        self.lbl_risk.setObjectName(_fromUtf8("lbl_risk"))
        self.gridLayout.addWidget(self.lbl_risk, 0, 11, 1, 1)
        self.dt_date = QtGui.QDateEdit(self.centralwidget)
        self.dt_date.setMinimumSize(QtCore.QSize(90, 0))
        self.dt_date.setDate(QtCore.QDate(1900, 1, 1))
        self.dt_date.setCalendarPopup(True)
        self.dt_date.setObjectName(_fromUtf8("dt_date"))
        self.gridLayout.addWidget(self.dt_date, 1, 0, 1, 1)
        self.cmb_category = QtGui.QComboBox(self.centralwidget)
        self.cmb_category.setMinimumSize(QtCore.QSize(120, 0))
        self.cmb_category.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.cmb_category.setEditable(True)
        self.cmb_category.setObjectName(_fromUtf8("cmb_category"))
        self.gridLayout.addWidget(self.cmb_category, 1, 1, 1, 1)
        self.cmb_subcategory = QtGui.QComboBox(self.centralwidget)
        self.cmb_subcategory.setMinimumSize(QtCore.QSize(100, 0))
        self.cmb_subcategory.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cmb_subcategory.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.cmb_subcategory.setEditable(True)
        self.cmb_subcategory.setObjectName(_fromUtf8("cmb_subcategory"))
        self.gridLayout.addWidget(self.cmb_subcategory, 1, 2, 1, 1)
        self.spn_amount = QtGui.QDoubleSpinBox(self.centralwidget)
        self.spn_amount.setMinimumSize(QtCore.QSize(70, 0))
        self.spn_amount.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.spn_amount.setDecimals(6)
        self.spn_amount.setMaximum(999999.99)
        self.spn_amount.setProperty("value", 0.0)
        self.spn_amount.setObjectName(_fromUtf8("spn_amount"))
        self.gridLayout.addWidget(self.spn_amount, 1, 3, 1, 1)
        self.txt_comment = QtGui.QLineEdit(self.centralwidget)
        self.txt_comment.setEnabled(True)
        self.txt_comment.setMinimumSize(QtCore.QSize(150, 0))
        self.txt_comment.setObjectName(_fromUtf8("txt_comment"))
        self.gridLayout.addWidget(self.txt_comment, 1, 4, 1, 1)
        self.cmb_market_code = QtGui.QComboBox(self.centralwidget)
        self.cmb_market_code.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.cmb_market_code.setEditable(True)
        self.cmb_market_code.setObjectName(_fromUtf8("cmb_market_code"))
        self.gridLayout.addWidget(self.cmb_market_code, 1, 5, 1, 1)
        self.cmb_stock_name = QtGui.QComboBox(self.centralwidget)
        self.cmb_stock_name.setMinimumSize(QtCore.QSize(120, 0))
        self.cmb_stock_name.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.cmb_stock_name.setEditable(True)
        self.cmb_stock_name.setObjectName(_fromUtf8("cmb_stock_name"))
        self.gridLayout.addWidget(self.cmb_stock_name, 1, 6, 1, 1)
        self.spn_quantity = QtGui.QSpinBox(self.centralwidget)
        self.spn_quantity.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        self.spn_quantity.setFont(font)
        self.spn_quantity.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.spn_quantity.setMaximum(999999)
        self.spn_quantity.setObjectName(_fromUtf8("spn_quantity"))
        self.gridLayout.addWidget(self.spn_quantity, 1, 7, 1, 1)
        self.spn_price = QtGui.QDoubleSpinBox(self.centralwidget)
        self.spn_price.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        self.spn_price.setFont(font)
        self.spn_price.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.spn_price.setDecimals(6)
        self.spn_price.setMaximum(999999.99)
        self.spn_price.setObjectName(_fromUtf8("spn_price"))
        self.gridLayout.addWidget(self.spn_price, 1, 8, 1, 1)
        self.spn_commission = QtGui.QDoubleSpinBox(self.centralwidget)
        self.spn_commission.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        self.spn_commission.setFont(font)
        self.spn_commission.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.spn_commission.setDecimals(6)
        self.spn_commission.setMaximum(999999.99)
        self.spn_commission.setObjectName(_fromUtf8("spn_commission"))
        self.gridLayout.addWidget(self.spn_commission, 1, 9, 1, 1)
        self.spn_tax = QtGui.QDoubleSpinBox(self.centralwidget)
        self.spn_tax.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        self.spn_tax.setFont(font)
        self.spn_tax.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.spn_tax.setDecimals(6)
        self.spn_tax.setMaximum(999999.99)
        self.spn_tax.setObjectName(_fromUtf8("spn_tax"))
        self.gridLayout.addWidget(self.spn_tax, 1, 10, 1, 1)
        self.spn_risk = QtGui.QDoubleSpinBox(self.centralwidget)
        self.spn_risk.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        self.spn_risk.setFont(font)
        self.spn_risk.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.spn_risk.setDecimals(6)
        self.spn_risk.setMaximum(999999.99)
        self.spn_risk.setObjectName(_fromUtf8("spn_risk"))
        self.gridLayout.addWidget(self.spn_risk, 1, 11, 1, 1)
        self.txt_market_description = QtGui.QLineEdit(self.centralwidget)
        self.txt_market_description.setObjectName(_fromUtf8("txt_market_description"))
        self.gridLayout.addWidget(self.txt_market_description, 2, 5, 1, 1)
        self.txt_stock_description = QtGui.QLineEdit(self.centralwidget)
        self.txt_stock_description.setObjectName(_fromUtf8("txt_stock_description"))
        self.gridLayout.addWidget(self.txt_stock_description, 2, 6, 1, 1)
        self.lbl_currency = QtGui.QLabel(self.centralwidget)
        self.lbl_currency.setObjectName(_fromUtf8("lbl_currency"))
        self.gridLayout.addWidget(self.lbl_currency, 3, 0, 1, 1)
        self.lbl_exchange_rate = QtGui.QLabel(self.centralwidget)
        self.lbl_exchange_rate.setObjectName(_fromUtf8("lbl_exchange_rate"))
        self.gridLayout.addWidget(self.lbl_exchange_rate, 3, 1, 1, 1)
        self.cmb_currency = QtGui.QComboBox(self.centralwidget)
        self.cmb_currency.setMinimumSize(QtCore.QSize(90, 0))
        self.cmb_currency.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cmb_currency.setObjectName(_fromUtf8("cmb_currency"))
        self.gridLayout.addWidget(self.cmb_currency, 4, 0, 1, 1)
        self.spn_exchange_rate = QtGui.QDoubleSpinBox(self.centralwidget)
        self.spn_exchange_rate.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        self.spn_exchange_rate.setFont(font)
        self.spn_exchange_rate.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.spn_exchange_rate.setDecimals(6)
        self.spn_exchange_rate.setMaximum(1000000.0)
        self.spn_exchange_rate.setObjectName(_fromUtf8("spn_exchange_rate"))
        self.gridLayout.addWidget(self.spn_exchange_rate, 4, 1, 1, 1)
        self.chk_manual_commission = QtGui.QCheckBox(self.centralwidget)
        self.chk_manual_commission.setChecked(False)
        self.chk_manual_commission.setObjectName(_fromUtf8("chk_manual_commission"))
        self.gridLayout.addWidget(self.chk_manual_commission, 2, 9, 1, 1)
        self.lbl_expiration = QtGui.QLabel(self.centralwidget)
        self.lbl_expiration.setFrameShape(QtGui.QFrame.NoFrame)
        self.lbl_expiration.setObjectName(_fromUtf8("lbl_expiration"))
        self.gridLayout.addWidget(self.lbl_expiration, 3, 6, 1, 1)
        self.dt_expiration = QtGui.QDateEdit(self.centralwidget)
        self.dt_expiration.setDateTime(QtCore.QDateTime(QtCore.QDate(1900, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dt_expiration.setDate(QtCore.QDate(1900, 1, 1))
        self.dt_expiration.setCalendarPopup(True)
        self.dt_expiration.setObjectName(_fromUtf8("dt_expiration"))
        self.gridLayout.addWidget(self.dt_expiration, 4, 6, 1, 1)
        self.spn_pool_trading = QtGui.QDoubleSpinBox(self.centralwidget)
        self.spn_pool_trading.setDecimals(6)
        self.spn_pool_trading.setMaximum(999999.99)
        self.spn_pool_trading.setObjectName(_fromUtf8("spn_pool_trading"))
        self.gridLayout.addWidget(self.spn_pool_trading, 4, 8, 1, 1)
        self.lbl_pool_trading = QtGui.QLabel(self.centralwidget)
        self.lbl_pool_trading.setObjectName(_fromUtf8("lbl_pool_trading"))
        self.gridLayout.addWidget(self.lbl_pool_trading, 3, 8, 1, 1)
        self.lblSpread = QtGui.QLabel(self.centralwidget)
        self.lblSpread.setObjectName(_fromUtf8("lblSpread"))
        self.gridLayout.addWidget(self.lblSpread, 3, 5, 1, 1)
        self.spnSpread = QtGui.QDoubleSpinBox(self.centralwidget)
        self.spnSpread.setDecimals(6)
        self.spnSpread.setMaximum(999999.99)
        self.spnSpread.setObjectName(_fromUtf8("spnSpread"))
        self.gridLayout.addWidget(self.spnSpread, 4, 5, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.btn_clear = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.btn_clear.setFont(font)
        self.btn_clear.setObjectName(_fromUtf8("btn_clear"))
        self.gridLayout_6.addWidget(self.btn_clear, 0, 4, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 0, 6, 1, 1)
        self.btn_exit = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.btn_exit.setFont(font)
        self.btn_exit.setObjectName(_fromUtf8("btn_exit"))
        self.gridLayout_6.addWidget(self.btn_exit, 0, 9, 1, 1)
        self.btn_add = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.btn_add.setFont(font)
        self.btn_add.setObjectName(_fromUtf8("btn_add"))
        self.gridLayout_6.addWidget(self.btn_add, 0, 0, 1, 1)
        self.btn_execute = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.btn_execute.setFont(font)
        self.btn_execute.setObjectName(_fromUtf8("btn_execute"))
        self.gridLayout_6.addWidget(self.btn_execute, 0, 5, 1, 1)
        self.lbl_infodetails = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.lbl_infodetails.setFont(font)
        self.lbl_infodetails.setObjectName(_fromUtf8("lbl_infodetails"))
        self.gridLayout_6.addWidget(self.lbl_infodetails, 0, 7, 1, 1)
        self.btn_update = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.btn_update.setFont(font)
        self.btn_update.setObjectName(_fromUtf8("btn_update"))
        self.gridLayout_6.addWidget(self.btn_update, 0, 1, 1, 1)
        self.btn_remove = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.btn_remove.setFont(font)
        self.btn_remove.setObjectName(_fromUtf8("btn_remove"))
        self.gridLayout_6.addWidget(self.btn_remove, 0, 2, 1, 1)
        self.btn_removelast = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Envy Code R"))
        self.btn_removelast.setFont(font)
        self.btn_removelast.setObjectName(_fromUtf8("btn_removelast"))
        self.gridLayout_6.addWidget(self.btn_removelast, 0, 3, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 0, 8, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_6)
        self.vl_table = QtGui.QVBoxLayout()
        self.vl_table.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.vl_table.setObjectName(_fromUtf8("vl_table"))
        self.verticalLayout.addLayout(self.vl_table)
        self.verticalLayout.setStretch(3, 1)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.dt_date, self.cmb_category)
        MainWindow.setTabOrder(self.cmb_category, self.cmb_subcategory)
        MainWindow.setTabOrder(self.cmb_subcategory, self.spn_amount)
        MainWindow.setTabOrder(self.spn_amount, self.txt_comment)
        MainWindow.setTabOrder(self.txt_comment, self.cmb_market_code)
        MainWindow.setTabOrder(self.cmb_market_code, self.cmb_stock_name)
        MainWindow.setTabOrder(self.cmb_stock_name, self.spn_quantity)
        MainWindow.setTabOrder(self.spn_quantity, self.spn_price)
        MainWindow.setTabOrder(self.spn_price, self.spn_commission)
        MainWindow.setTabOrder(self.spn_commission, self.chk_manual_commission)
        MainWindow.setTabOrder(self.chk_manual_commission, self.spn_tax)
        MainWindow.setTabOrder(self.spn_tax, self.spn_risk)
        MainWindow.setTabOrder(self.spn_risk, self.txt_market_description)
        MainWindow.setTabOrder(self.txt_market_description, self.txt_stock_description)
        MainWindow.setTabOrder(self.txt_stock_description, self.dt_expiration)
        MainWindow.setTabOrder(self.dt_expiration, self.cmb_currency)
        MainWindow.setTabOrder(self.cmb_currency, self.spn_exchange_rate)
        MainWindow.setTabOrder(self.spn_exchange_rate, self.btn_add)
        MainWindow.setTabOrder(self.btn_add, self.btn_update)
        MainWindow.setTabOrder(self.btn_update, self.btn_remove)
        MainWindow.setTabOrder(self.btn_remove, self.btn_removelast)
        MainWindow.setTabOrder(self.btn_removelast, self.btn_clear)
        MainWindow.setTabOrder(self.btn_clear, self.btn_execute)
        MainWindow.setTabOrder(self.btn_execute, self.btn_exit)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_check.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_infofinance.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_account.setText(QtGui.QApplication.translate("MainWindow", "Account", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_date.setText(QtGui.QApplication.translate("MainWindow", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_category.setText(QtGui.QApplication.translate("MainWindow", "Category", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_subcategory.setText(QtGui.QApplication.translate("MainWindow", "Subcategory", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_amount.setText(QtGui.QApplication.translate("MainWindow", "Amount", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_comment.setText(QtGui.QApplication.translate("MainWindow", "Comment", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_marketcode.setText(QtGui.QApplication.translate("MainWindow", "Market code", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_stockname.setText(QtGui.QApplication.translate("MainWindow", "Stock name", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_quantity.setText(QtGui.QApplication.translate("MainWindow", "Quantity", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_price.setText(QtGui.QApplication.translate("MainWindow", "Price", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_commission.setText(QtGui.QApplication.translate("MainWindow", "Commission", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_tax.setText(QtGui.QApplication.translate("MainWindow", "Tax（％）", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_risk.setText(QtGui.QApplication.translate("MainWindow", "Risk (%)", None, QtGui.QApplication.UnicodeUTF8))
        self.dt_date.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "yyyy-MM-dd", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_currency.setText(QtGui.QApplication.translate("MainWindow", "Currency", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_exchange_rate.setText(QtGui.QApplication.translate("MainWindow", "Exchange rate", None, QtGui.QApplication.UnicodeUTF8))
        self.chk_manual_commission.setText(QtGui.QApplication.translate("MainWindow", "Automatic", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_expiration.setText(QtGui.QApplication.translate("MainWindow", "Expires on", None, QtGui.QApplication.UnicodeUTF8))
        self.dt_expiration.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "yyyy-MM-dd", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_pool_trading.setText(QtGui.QApplication.translate("MainWindow", "Pool", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSpread.setText(QtGui.QApplication.translate("MainWindow", "Spread", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_clear.setText(QtGui.QApplication.translate("MainWindow", "&Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_exit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_add.setText(QtGui.QApplication.translate("MainWindow", "&Add", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_execute.setText(QtGui.QApplication.translate("MainWindow", "E&xecute", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_infodetails.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_update.setText(QtGui.QApplication.translate("MainWindow", "&Update", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_remove.setText(QtGui.QApplication.translate("MainWindow", "&Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_removelast.setText(QtGui.QApplication.translate("MainWindow", "Remove &last", None, QtGui.QApplication.UnicodeUTF8))

