BEGIN;
drop table T_FINANCE cascade;
drop table T_SUBCATEGORY cascade;
drop table T_CATEGORY cascade;
drop table T_ACCOUNT cascade;
drop table T_STOCK cascade;
drop table T_STOCK_NAME cascade;
drop table T_MARKET cascade;
drop table T_MARGIN_TYPE cascade;
drop table T_MARGIN cascade;
drop table T_STOCK_CURRENT;
drop table T_TRADE cascade;
drop table T_RATE cascade;
drop table T_CURRENCY_EXCHANGE cascade;
drop table T_CURRENCY cascade;
drop table T_FORMULA cascade;
drop table T_DRAWDOWN cascade;
COMMIT;
