BEGIN;
drop view V_FINANCE;
drop view V_SUBCATEGORY;
drop view V_CATEGORY;
drop view V_ACCOUNT;
drop view V_STOCK;
drop view V_STOCK_NAME;
drop view V_MARKET;
drop view V_MARGIN_TYPE;
drop view V_MARGIN;
drop view V_STOCK_CURRENT;
drop view V_TRADE;
drop view V_RATE;
drop view V_CURRENCY_EXCHANGE;
drop view V_CURRENCY;
drop view V_FORMULA;
COMMIT;
