BEGIN;
drop table T_FINANCE cascade;
drop table T_SUBCATEGORY cascade;
drop table T_CATEGORY cascade;
drop table T_ACCOUNT cascade;
drop table T_STOCK cascade;
drop table T_STOCK_NAME cascade;
drop table T_MARKET cascade;
drop table T_MARGIN_TYPE cascade;
drop table T_MARGIN cascade;
drop table T_STOCK_CURRENT;
drop table T_TRADE cascade;
drop table T_RATES cascade;
COMMIT;
