BEGIN;
truncate table T_FINANCE cascade;
truncate table T_SUB_CATEGORY cascade;
truncate table T_CATEGORY cascade;
truncate table T_ACCOUNT cascade;
truncate table T_STOCK cascade;
truncate table T_STOCK_NAME cascade;
truncate table T_MARKET cascade;
truncate table T_MARGIN cascade;
truncate table T_MARGIN_TYPE cascade;
truncate table T_STOCK_CURRENT;
truncate table T_TRADE cascade;
drop table T_FINANCE cascade;
drop table T_SUB_CATEGORY cascade;
drop table T_CATEGORY cascade;
drop table T_ACCOUNT cascade;
drop table T_STOCK cascade;
drop table T_STOCK_NAME cascade;
drop table T_MARKET cascade;
drop table T_MARGIN_TYPE cascade;
drop table T_MARGIN cascade;
drop table T_STOCK_CURRENT;
drop table T_TRADE cascade;
COMMIT;
