# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewpyqt_dialog_emma.ui'
#
# Created: Tue Mar 18 19:42:41 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogEmma(object):
    def setupUi(self, DialogEmma):
        DialogEmma.setObjectName(_fromUtf8("DialogEmma"))
        DialogEmma.resize(1196, 565)
        self.gridLayout_3 = QtGui.QGridLayout(DialogEmma)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.grp_input = QtGui.QGroupBox(DialogEmma)
        self.grp_input.setObjectName(_fromUtf8("grp_input"))
        self.verticalLayout = QtGui.QVBoxLayout(self.grp_input)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lbl_account_to = QtGui.QLabel(self.grp_input)
        self.lbl_account_to.setObjectName(_fromUtf8("lbl_account_to"))
        self.gridLayout_2.addWidget(self.lbl_account_to, 2, 0, 1, 1)
        self.txt_quantity_recommended = QtGui.QLineEdit(self.grp_input)
        self.txt_quantity_recommended.setObjectName(_fromUtf8("txt_quantity_recommended"))
        self.gridLayout_2.addWidget(self.txt_quantity_recommended, 3, 1, 1, 1)
        self.lbl_quantity_recommended = QtGui.QLabel(self.grp_input)
        self.lbl_quantity_recommended.setObjectName(_fromUtf8("lbl_quantity_recommended"))
        self.gridLayout_2.addWidget(self.lbl_quantity_recommended, 2, 1, 1, 1)
        self.lbl_price_orig = QtGui.QLabel(self.grp_input)
        self.lbl_price_orig.setObjectName(_fromUtf8("lbl_price_orig"))
        self.gridLayout_2.addWidget(self.lbl_price_orig, 0, 6, 1, 1)
        self.spn_price_orig = QtGui.QDoubleSpinBox(self.grp_input)
        self.spn_price_orig.setDecimals(6)
        self.spn_price_orig.setMaximum(99.999999)
        self.spn_price_orig.setObjectName(_fromUtf8("spn_price_orig"))
        self.gridLayout_2.addWidget(self.spn_price_orig, 1, 6, 1, 1)
        self.lbl_pool = QtGui.QLabel(self.grp_input)
        self.lbl_pool.setObjectName(_fromUtf8("lbl_pool"))
        self.gridLayout_2.addWidget(self.lbl_pool, 0, 1, 1, 1)
        self.lbl_tax = QtGui.QLabel(self.grp_input)
        self.lbl_tax.setObjectName(_fromUtf8("lbl_tax"))
        self.gridLayout_2.addWidget(self.lbl_tax, 0, 4, 1, 1)
        self.lbl_risk = QtGui.QLabel(self.grp_input)
        self.lbl_risk.setObjectName(_fromUtf8("lbl_risk"))
        self.gridLayout_2.addWidget(self.lbl_risk, 0, 2, 1, 1)
        self.spn_pool = QtGui.QDoubleSpinBox(self.grp_input)
        self.spn_pool.setDecimals(6)
        self.spn_pool.setMaximum(99.999999)
        self.spn_pool.setObjectName(_fromUtf8("spn_pool"))
        self.gridLayout_2.addWidget(self.spn_pool, 1, 1, 1, 1)
        self.cmb_account_to = QtGui.QComboBox(self.grp_input)
        self.cmb_account_to.setObjectName(_fromUtf8("cmb_account_to"))
        self.gridLayout_2.addWidget(self.cmb_account_to, 3, 0, 1, 1)
        self.cmb_currency_from = QtGui.QComboBox(self.grp_input)
        self.cmb_currency_from.setObjectName(_fromUtf8("cmb_currency_from"))
        self.gridLayout_2.addWidget(self.cmb_currency_from, 1, 5, 1, 1)
        self.lbl_account_from = QtGui.QLabel(self.grp_input)
        self.lbl_account_from.setObjectName(_fromUtf8("lbl_account_from"))
        self.gridLayout_2.addWidget(self.lbl_account_from, 0, 0, 1, 1)
        self.spn_commission = QtGui.QDoubleSpinBox(self.grp_input)
        self.spn_commission.setDecimals(6)
        self.spn_commission.setMaximum(99.999999)
        self.spn_commission.setObjectName(_fromUtf8("spn_commission"))
        self.gridLayout_2.addWidget(self.spn_commission, 1, 3, 1, 1)
        self.lbl_commission = QtGui.QLabel(self.grp_input)
        self.lbl_commission.setObjectName(_fromUtf8("lbl_commission"))
        self.gridLayout_2.addWidget(self.lbl_commission, 0, 3, 1, 1)
        self.cmb_account_from = QtGui.QComboBox(self.grp_input)
        self.cmb_account_from.setObjectName(_fromUtf8("cmb_account_from"))
        self.gridLayout_2.addWidget(self.cmb_account_from, 1, 0, 1, 1)
        self.spn_tax = QtGui.QDoubleSpinBox(self.grp_input)
        self.spn_tax.setDecimals(6)
        self.spn_tax.setMaximum(99.999999)
        self.spn_tax.setObjectName(_fromUtf8("spn_tax"))
        self.gridLayout_2.addWidget(self.spn_tax, 1, 4, 1, 1)
        self.spn_risk = QtGui.QDoubleSpinBox(self.grp_input)
        self.spn_risk.setDecimals(6)
        self.spn_risk.setMaximum(99.999999)
        self.spn_risk.setObjectName(_fromUtf8("spn_risk"))
        self.gridLayout_2.addWidget(self.spn_risk, 1, 2, 1, 1)
        self.lbl_currency = QtGui.QLabel(self.grp_input)
        self.lbl_currency.setObjectName(_fromUtf8("lbl_currency"))
        self.gridLayout_2.addWidget(self.lbl_currency, 0, 5, 1, 1)
        self.lbl_currency_to = QtGui.QLabel(self.grp_input)
        self.lbl_currency_to.setObjectName(_fromUtf8("lbl_currency_to"))
        self.gridLayout_2.addWidget(self.lbl_currency_to, 2, 5, 1, 1)
        self.cmb_currency_to = QtGui.QComboBox(self.grp_input)
        self.cmb_currency_to.setObjectName(_fromUtf8("cmb_currency_to"))
        self.gridLayout_2.addWidget(self.cmb_currency_to, 3, 5, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_2.addWidget(self.grp_input)
        self.grp_summary = QtGui.QGroupBox(DialogEmma)
        self.grp_summary.setObjectName(_fromUtf8("grp_summary"))
        self.gridLayout = QtGui.QGridLayout(self.grp_summary)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.txt_summary = QtGui.QTextEdit(self.grp_summary)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Inconsolata"))
        font.setPointSize(14)
        self.txt_summary.setFont(font)
        self.txt_summary.setFrameShadow(QtGui.QFrame.Raised)
        self.txt_summary.setReadOnly(True)
        self.txt_summary.setObjectName(_fromUtf8("txt_summary"))
        self.gridLayout.addWidget(self.txt_summary, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.grp_summary)
        self.verticalLayout_2.setStretch(1, 1)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.btn_box = QtGui.QDialogButtonBox(DialogEmma)
        self.btn_box.setOrientation(QtCore.Qt.Horizontal)
        self.btn_box.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Close)
        self.btn_box.setObjectName(_fromUtf8("btn_box"))
        self.gridLayout_3.addWidget(self.btn_box, 1, 0, 1, 1)

        self.retranslateUi(DialogEmma)
        QtCore.QObject.connect(self.btn_box, QtCore.SIGNAL(_fromUtf8("accepted()")), DialogEmma.accept)
        QtCore.QObject.connect(self.btn_box, QtCore.SIGNAL(_fromUtf8("rejected()")), DialogEmma.reject)
        QtCore.QObject.connect(self.btn_box, QtCore.SIGNAL(_fromUtf8("clicked(QAbstractButton*)")), DialogEmma.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogEmma)

    def retranslateUi(self, DialogEmma):
        DialogEmma.setWindowTitle(_translate("DialogEmma", "Dialog", None))
        self.grp_input.setTitle(_translate("DialogEmma", "Input", None))
        self.lbl_account_to.setText(_translate("DialogEmma", "Account_to", None))
        self.lbl_quantity_recommended.setText(_translate("DialogEmma", "Recommended quantity", None))
        self.lbl_price_orig.setText(_translate("DialogEmma", "Price (orig curr)", None))
        self.lbl_pool.setText(_translate("DialogEmma", "Pool (a 25% safety margin will be deducted automatically)", None))
        self.lbl_tax.setText(_translate("DialogEmma", "Tax", None))
        self.lbl_risk.setText(_translate("DialogEmma", "Risk", None))
        self.lbl_account_from.setText(_translate("DialogEmma", "Account from", None))
        self.lbl_commission.setText(_translate("DialogEmma", "Commission", None))
        self.lbl_currency.setText(_translate("DialogEmma", "Currency from", None))
        self.lbl_currency_to.setText(_translate("DialogEmma", "Currency to", None))
        self.grp_summary.setTitle(_translate("DialogEmma", "Summary", None))

