# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewpyqt.ui'
#
# Created: Mon Aug 27 19:26:18 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1440, 900)
        MainWindow.setTabShape(QtGui.QTabWidget.Triangular)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_exit = QtGui.QPushButton(self.centralwidget)
        self.btn_exit.setObjectName(_fromUtf8("btn_exit"))
        self.horizontalLayout.addWidget(self.btn_exit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tab_main = QtGui.QTabWidget(self.centralwidget)
        self.tab_main.setMinimumSize(QtCore.QSize(0, 521))
        self.tab_main.setTabShape(QtGui.QTabWidget.Rounded)
        self.tab_main.setElideMode(QtCore.Qt.ElideNone)
        self.tab_main.setDocumentMode(True)
        self.tab_main.setMovable(True)
        self.tab_main.setObjectName(_fromUtf8("tab_main"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.grp_invest_buy = QtGui.QGroupBox(self.tab)
        self.grp_invest_buy.setObjectName(_fromUtf8("grp_invest_buy"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.grp_invest_buy)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lbl_commission = QtGui.QLabel(self.grp_invest_buy)
        self.lbl_commission.setObjectName(_fromUtf8("lbl_commission"))
        self.gridLayout_2.addWidget(self.lbl_commission, 0, 3, 1, 1)
        self.lbl_pool = QtGui.QLabel(self.grp_invest_buy)
        self.lbl_pool.setObjectName(_fromUtf8("lbl_pool"))
        self.gridLayout_2.addWidget(self.lbl_pool, 0, 1, 1, 1)
        self.txt_traded_capital = QtGui.QLineEdit(self.grp_invest_buy)
        self.txt_traded_capital.setObjectName(_fromUtf8("txt_traded_capital"))
        self.gridLayout_2.addWidget(self.txt_traded_capital, 1, 2, 1, 1)
        self.lbl_price = QtGui.QLabel(self.grp_invest_buy)
        self.lbl_price.setObjectName(_fromUtf8("lbl_price"))
        self.gridLayout_2.addWidget(self.lbl_price, 0, 5, 1, 1)
        self.lbl_traded_capital = QtGui.QLabel(self.grp_invest_buy)
        self.lbl_traded_capital.setObjectName(_fromUtf8("lbl_traded_capital"))
        self.gridLayout_2.addWidget(self.lbl_traded_capital, 0, 2, 1, 1)
        self.txt_pool = QtGui.QLineEdit(self.grp_invest_buy)
        self.txt_pool.setObjectName(_fromUtf8("txt_pool"))
        self.gridLayout_2.addWidget(self.txt_pool, 1, 1, 1, 1)
        self.lbl_price_2 = QtGui.QLabel(self.grp_invest_buy)
        self.lbl_price_2.setObjectName(_fromUtf8("lbl_price_2"))
        self.gridLayout_2.addWidget(self.lbl_price_2, 2, 5, 1, 1)
        self.txt_traded_capital_2 = QtGui.QLineEdit(self.grp_invest_buy)
        self.txt_traded_capital_2.setEnabled(True)
        self.txt_traded_capital_2.setAutoFillBackground(False)
        self.txt_traded_capital_2.setStyleSheet(_fromUtf8("background : transparent;"))
        self.txt_traded_capital_2.setFrame(True)
        self.txt_traded_capital_2.setReadOnly(True)
        self.txt_traded_capital_2.setObjectName(_fromUtf8("txt_traded_capital_2"))
        self.gridLayout_2.addWidget(self.txt_traded_capital_2, 3, 2, 1, 1)
        self.lbl_tax_2 = QtGui.QLabel(self.grp_invest_buy)
        self.lbl_tax_2.setObjectName(_fromUtf8("lbl_tax_2"))
        self.gridLayout_2.addWidget(self.lbl_tax_2, 2, 4, 1, 1)
        self.lbl_risk_2 = QtGui.QLabel(self.grp_invest_buy)
        self.lbl_risk_2.setObjectName(_fromUtf8("lbl_risk_2"))
        self.gridLayout_2.addWidget(self.lbl_risk_2, 2, 0, 1, 1)
        self.txt_pool_2 = QtGui.QLineEdit(self.grp_invest_buy)
        self.txt_pool_2.setEnabled(True)
        self.txt_pool_2.setAutoFillBackground(False)
        self.txt_pool_2.setStyleSheet(_fromUtf8("background : transparent;"))
        self.txt_pool_2.setFrame(True)
        self.txt_pool_2.setReadOnly(True)
        self.txt_pool_2.setObjectName(_fromUtf8("txt_pool_2"))
        self.gridLayout_2.addWidget(self.txt_pool_2, 3, 1, 1, 1)
        self.txt_commission = QtGui.QLineEdit(self.grp_invest_buy)
        self.txt_commission.setObjectName(_fromUtf8("txt_commission"))
        self.gridLayout_2.addWidget(self.txt_commission, 1, 3, 1, 1)
        self.txt_tax = QtGui.QLineEdit(self.grp_invest_buy)
        self.txt_tax.setObjectName(_fromUtf8("txt_tax"))
        self.gridLayout_2.addWidget(self.txt_tax, 1, 4, 1, 1)
        self.txt_price = QtGui.QLineEdit(self.grp_invest_buy)
        self.txt_price.setObjectName(_fromUtf8("txt_price"))
        self.gridLayout_2.addWidget(self.txt_price, 1, 5, 1, 1)
        self.txt_tax_2 = QtGui.QLineEdit(self.grp_invest_buy)
        self.txt_tax_2.setEnabled(True)
        self.txt_tax_2.setAutoFillBackground(False)
        self.txt_tax_2.setStyleSheet(_fromUtf8("background : transparent;"))
        self.txt_tax_2.setFrame(True)
        self.txt_tax_2.setReadOnly(True)
        self.txt_tax_2.setObjectName(_fromUtf8("txt_tax_2"))
        self.gridLayout_2.addWidget(self.txt_tax_2, 3, 4, 1, 1)
        self.txt_risk = QtGui.QLineEdit(self.grp_invest_buy)
        self.txt_risk.setObjectName(_fromUtf8("txt_risk"))
        self.gridLayout_2.addWidget(self.txt_risk, 1, 0, 1, 1)
        self.lbl_tax = QtGui.QLabel(self.grp_invest_buy)
        self.lbl_tax.setObjectName(_fromUtf8("lbl_tax"))
        self.gridLayout_2.addWidget(self.lbl_tax, 0, 4, 1, 1)
        self.lbl_pool_2 = QtGui.QLabel(self.grp_invest_buy)
        self.lbl_pool_2.setObjectName(_fromUtf8("lbl_pool_2"))
        self.gridLayout_2.addWidget(self.lbl_pool_2, 2, 1, 1, 1)
        self.lbl_traded_capital_2 = QtGui.QLabel(self.grp_invest_buy)
        self.lbl_traded_capital_2.setObjectName(_fromUtf8("lbl_traded_capital_2"))
        self.gridLayout_2.addWidget(self.lbl_traded_capital_2, 2, 2, 1, 1)
        self.txt_risk_2 = QtGui.QLineEdit(self.grp_invest_buy)
        self.txt_risk_2.setEnabled(True)
        self.txt_risk_2.setAutoFillBackground(False)
        self.txt_risk_2.setStyleSheet(_fromUtf8("background : transparent;"))
        self.txt_risk_2.setFrame(True)
        self.txt_risk_2.setReadOnly(True)
        self.txt_risk_2.setObjectName(_fromUtf8("txt_risk_2"))
        self.gridLayout_2.addWidget(self.txt_risk_2, 3, 0, 1, 1)
        self.txt_price_2 = QtGui.QLineEdit(self.grp_invest_buy)
        self.txt_price_2.setEnabled(True)
        self.txt_price_2.setAutoFillBackground(False)
        self.txt_price_2.setStyleSheet(_fromUtf8("background : transparent;"))
        self.txt_price_2.setFrame(True)
        self.txt_price_2.setReadOnly(True)
        self.txt_price_2.setObjectName(_fromUtf8("txt_price_2"))
        self.gridLayout_2.addWidget(self.txt_price_2, 3, 5, 1, 1)
        self.lbl_risk = QtGui.QLabel(self.grp_invest_buy)
        self.lbl_risk.setObjectName(_fromUtf8("lbl_risk"))
        self.gridLayout_2.addWidget(self.lbl_risk, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.verticalLayout_5.addWidget(self.grp_invest_buy)
        self.grp_invest_sell = QtGui.QGroupBox(self.tab)
        self.grp_invest_sell.setObjectName(_fromUtf8("grp_invest_sell"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.grp_invest_sell)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lbl_commission_2 = QtGui.QLabel(self.grp_invest_sell)
        self.lbl_commission_2.setObjectName(_fromUtf8("lbl_commission_2"))
        self.gridLayout_4.addWidget(self.lbl_commission_2, 0, 3, 1, 1)
        self.lbl_pool_3 = QtGui.QLabel(self.grp_invest_sell)
        self.lbl_pool_3.setObjectName(_fromUtf8("lbl_pool_3"))
        self.gridLayout_4.addWidget(self.lbl_pool_3, 0, 1, 1, 1)
        self.txt_traded_capital_3 = QtGui.QLineEdit(self.grp_invest_sell)
        self.txt_traded_capital_3.setObjectName(_fromUtf8("txt_traded_capital_3"))
        self.gridLayout_4.addWidget(self.txt_traded_capital_3, 1, 2, 1, 1)
        self.lbl_price_3 = QtGui.QLabel(self.grp_invest_sell)
        self.lbl_price_3.setObjectName(_fromUtf8("lbl_price_3"))
        self.gridLayout_4.addWidget(self.lbl_price_3, 0, 5, 1, 1)
        self.lbl_traded_capital_3 = QtGui.QLabel(self.grp_invest_sell)
        self.lbl_traded_capital_3.setObjectName(_fromUtf8("lbl_traded_capital_3"))
        self.gridLayout_4.addWidget(self.lbl_traded_capital_3, 0, 2, 1, 1)
        self.txt_pool_3 = QtGui.QLineEdit(self.grp_invest_sell)
        self.txt_pool_3.setObjectName(_fromUtf8("txt_pool_3"))
        self.gridLayout_4.addWidget(self.txt_pool_3, 1, 1, 1, 1)
        self.lbl_price_4 = QtGui.QLabel(self.grp_invest_sell)
        self.lbl_price_4.setObjectName(_fromUtf8("lbl_price_4"))
        self.gridLayout_4.addWidget(self.lbl_price_4, 2, 5, 1, 1)
        self.txt_traded_capital_4 = QtGui.QLineEdit(self.grp_invest_sell)
        self.txt_traded_capital_4.setEnabled(True)
        self.txt_traded_capital_4.setAutoFillBackground(False)
        self.txt_traded_capital_4.setStyleSheet(_fromUtf8("background : transparent;"))
        self.txt_traded_capital_4.setFrame(True)
        self.txt_traded_capital_4.setReadOnly(True)
        self.txt_traded_capital_4.setObjectName(_fromUtf8("txt_traded_capital_4"))
        self.gridLayout_4.addWidget(self.txt_traded_capital_4, 3, 2, 1, 1)
        self.lbl_tax_3 = QtGui.QLabel(self.grp_invest_sell)
        self.lbl_tax_3.setObjectName(_fromUtf8("lbl_tax_3"))
        self.gridLayout_4.addWidget(self.lbl_tax_3, 2, 4, 1, 1)
        self.lbl_risk_3 = QtGui.QLabel(self.grp_invest_sell)
        self.lbl_risk_3.setObjectName(_fromUtf8("lbl_risk_3"))
        self.gridLayout_4.addWidget(self.lbl_risk_3, 2, 0, 1, 1)
        self.txt_pool_4 = QtGui.QLineEdit(self.grp_invest_sell)
        self.txt_pool_4.setEnabled(True)
        self.txt_pool_4.setAutoFillBackground(False)
        self.txt_pool_4.setStyleSheet(_fromUtf8("background : transparent;"))
        self.txt_pool_4.setFrame(True)
        self.txt_pool_4.setReadOnly(True)
        self.txt_pool_4.setObjectName(_fromUtf8("txt_pool_4"))
        self.gridLayout_4.addWidget(self.txt_pool_4, 3, 1, 1, 1)
        self.txt_commission_2 = QtGui.QLineEdit(self.grp_invest_sell)
        self.txt_commission_2.setObjectName(_fromUtf8("txt_commission_2"))
        self.gridLayout_4.addWidget(self.txt_commission_2, 1, 3, 1, 1)
        self.txt_tax_3 = QtGui.QLineEdit(self.grp_invest_sell)
        self.txt_tax_3.setObjectName(_fromUtf8("txt_tax_3"))
        self.gridLayout_4.addWidget(self.txt_tax_3, 1, 4, 1, 1)
        self.txt_price_3 = QtGui.QLineEdit(self.grp_invest_sell)
        self.txt_price_3.setObjectName(_fromUtf8("txt_price_3"))
        self.gridLayout_4.addWidget(self.txt_price_3, 1, 5, 1, 1)
        self.txt_tax_4 = QtGui.QLineEdit(self.grp_invest_sell)
        self.txt_tax_4.setEnabled(True)
        self.txt_tax_4.setAutoFillBackground(False)
        self.txt_tax_4.setStyleSheet(_fromUtf8("background : transparent;"))
        self.txt_tax_4.setFrame(True)
        self.txt_tax_4.setReadOnly(True)
        self.txt_tax_4.setObjectName(_fromUtf8("txt_tax_4"))
        self.gridLayout_4.addWidget(self.txt_tax_4, 3, 4, 1, 1)
        self.txt_risk_3 = QtGui.QLineEdit(self.grp_invest_sell)
        self.txt_risk_3.setObjectName(_fromUtf8("txt_risk_3"))
        self.gridLayout_4.addWidget(self.txt_risk_3, 1, 0, 1, 1)
        self.lbl_tax_4 = QtGui.QLabel(self.grp_invest_sell)
        self.lbl_tax_4.setObjectName(_fromUtf8("lbl_tax_4"))
        self.gridLayout_4.addWidget(self.lbl_tax_4, 0, 4, 1, 1)
        self.lbl_pool_4 = QtGui.QLabel(self.grp_invest_sell)
        self.lbl_pool_4.setObjectName(_fromUtf8("lbl_pool_4"))
        self.gridLayout_4.addWidget(self.lbl_pool_4, 2, 1, 1, 1)
        self.lbl_traded_capital_4 = QtGui.QLabel(self.grp_invest_sell)
        self.lbl_traded_capital_4.setObjectName(_fromUtf8("lbl_traded_capital_4"))
        self.gridLayout_4.addWidget(self.lbl_traded_capital_4, 2, 2, 1, 1)
        self.txt_risk_4 = QtGui.QLineEdit(self.grp_invest_sell)
        self.txt_risk_4.setEnabled(True)
        self.txt_risk_4.setAutoFillBackground(False)
        self.txt_risk_4.setStyleSheet(_fromUtf8("background : transparent;"))
        self.txt_risk_4.setFrame(True)
        self.txt_risk_4.setReadOnly(True)
        self.txt_risk_4.setObjectName(_fromUtf8("txt_risk_4"))
        self.gridLayout_4.addWidget(self.txt_risk_4, 3, 0, 1, 1)
        self.txt_price_4 = QtGui.QLineEdit(self.grp_invest_sell)
        self.txt_price_4.setEnabled(True)
        self.txt_price_4.setAutoFillBackground(False)
        self.txt_price_4.setStyleSheet(_fromUtf8("background : transparent;"))
        self.txt_price_4.setFrame(True)
        self.txt_price_4.setReadOnly(True)
        self.txt_price_4.setObjectName(_fromUtf8("txt_price_4"))
        self.gridLayout_4.addWidget(self.txt_price_4, 3, 5, 1, 1)
        self.lbl_risk_4 = QtGui.QLabel(self.grp_invest_sell)
        self.lbl_risk_4.setObjectName(_fromUtf8("lbl_risk_4"))
        self.gridLayout_4.addWidget(self.lbl_risk_4, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_4)
        self.verticalLayout_5.addWidget(self.grp_invest_sell)
        self.grp_readjust = QtGui.QGroupBox(self.tab)
        self.grp_readjust.setObjectName(_fromUtf8("grp_readjust"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.grp_readjust)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.lbl_commission_3 = QtGui.QLabel(self.grp_readjust)
        self.lbl_commission_3.setObjectName(_fromUtf8("lbl_commission_3"))
        self.gridLayout_5.addWidget(self.lbl_commission_3, 0, 3, 1, 1)
        self.lbl_pool_5 = QtGui.QLabel(self.grp_readjust)
        self.lbl_pool_5.setObjectName(_fromUtf8("lbl_pool_5"))
        self.gridLayout_5.addWidget(self.lbl_pool_5, 0, 1, 1, 1)
        self.txt_traded_capital_5 = QtGui.QLineEdit(self.grp_readjust)
        self.txt_traded_capital_5.setObjectName(_fromUtf8("txt_traded_capital_5"))
        self.gridLayout_5.addWidget(self.txt_traded_capital_5, 1, 2, 1, 1)
        self.lbl_price_5 = QtGui.QLabel(self.grp_readjust)
        self.lbl_price_5.setObjectName(_fromUtf8("lbl_price_5"))
        self.gridLayout_5.addWidget(self.lbl_price_5, 0, 5, 1, 1)
        self.lbl_traded_capital_5 = QtGui.QLabel(self.grp_readjust)
        self.lbl_traded_capital_5.setObjectName(_fromUtf8("lbl_traded_capital_5"))
        self.gridLayout_5.addWidget(self.lbl_traded_capital_5, 0, 2, 1, 1)
        self.txt_pool_5 = QtGui.QLineEdit(self.grp_readjust)
        self.txt_pool_5.setObjectName(_fromUtf8("txt_pool_5"))
        self.gridLayout_5.addWidget(self.txt_pool_5, 1, 1, 1, 1)
        self.lbl_price_6 = QtGui.QLabel(self.grp_readjust)
        self.lbl_price_6.setObjectName(_fromUtf8("lbl_price_6"))
        self.gridLayout_5.addWidget(self.lbl_price_6, 2, 5, 1, 1)
        self.txt_traded_capital_6 = QtGui.QLineEdit(self.grp_readjust)
        self.txt_traded_capital_6.setEnabled(True)
        self.txt_traded_capital_6.setAutoFillBackground(False)
        self.txt_traded_capital_6.setStyleSheet(_fromUtf8("background : transparent;"))
        self.txt_traded_capital_6.setFrame(True)
        self.txt_traded_capital_6.setReadOnly(True)
        self.txt_traded_capital_6.setObjectName(_fromUtf8("txt_traded_capital_6"))
        self.gridLayout_5.addWidget(self.txt_traded_capital_6, 3, 2, 1, 1)
        self.lbl_tax_5 = QtGui.QLabel(self.grp_readjust)
        self.lbl_tax_5.setObjectName(_fromUtf8("lbl_tax_5"))
        self.gridLayout_5.addWidget(self.lbl_tax_5, 2, 4, 1, 1)
        self.lbl_risk_5 = QtGui.QLabel(self.grp_readjust)
        self.lbl_risk_5.setObjectName(_fromUtf8("lbl_risk_5"))
        self.gridLayout_5.addWidget(self.lbl_risk_5, 2, 0, 1, 1)
        self.txt_pool_6 = QtGui.QLineEdit(self.grp_readjust)
        self.txt_pool_6.setEnabled(True)
        self.txt_pool_6.setAutoFillBackground(False)
        self.txt_pool_6.setStyleSheet(_fromUtf8("background : transparent;"))
        self.txt_pool_6.setFrame(True)
        self.txt_pool_6.setReadOnly(True)
        self.txt_pool_6.setObjectName(_fromUtf8("txt_pool_6"))
        self.gridLayout_5.addWidget(self.txt_pool_6, 3, 1, 1, 1)
        self.txt_commission_3 = QtGui.QLineEdit(self.grp_readjust)
        self.txt_commission_3.setObjectName(_fromUtf8("txt_commission_3"))
        self.gridLayout_5.addWidget(self.txt_commission_3, 1, 3, 1, 1)
        self.txt_tax_5 = QtGui.QLineEdit(self.grp_readjust)
        self.txt_tax_5.setObjectName(_fromUtf8("txt_tax_5"))
        self.gridLayout_5.addWidget(self.txt_tax_5, 1, 4, 1, 1)
        self.txt_price_5 = QtGui.QLineEdit(self.grp_readjust)
        self.txt_price_5.setObjectName(_fromUtf8("txt_price_5"))
        self.gridLayout_5.addWidget(self.txt_price_5, 1, 5, 1, 1)
        self.txt_tax_6 = QtGui.QLineEdit(self.grp_readjust)
        self.txt_tax_6.setEnabled(True)
        self.txt_tax_6.setAutoFillBackground(False)
        self.txt_tax_6.setStyleSheet(_fromUtf8("background : transparent;"))
        self.txt_tax_6.setFrame(True)
        self.txt_tax_6.setReadOnly(True)
        self.txt_tax_6.setObjectName(_fromUtf8("txt_tax_6"))
        self.gridLayout_5.addWidget(self.txt_tax_6, 3, 4, 1, 1)
        self.txt_risk_5 = QtGui.QLineEdit(self.grp_readjust)
        self.txt_risk_5.setObjectName(_fromUtf8("txt_risk_5"))
        self.gridLayout_5.addWidget(self.txt_risk_5, 1, 0, 1, 1)
        self.lbl_tax_6 = QtGui.QLabel(self.grp_readjust)
        self.lbl_tax_6.setObjectName(_fromUtf8("lbl_tax_6"))
        self.gridLayout_5.addWidget(self.lbl_tax_6, 0, 4, 1, 1)
        self.lbl_pool_6 = QtGui.QLabel(self.grp_readjust)
        self.lbl_pool_6.setObjectName(_fromUtf8("lbl_pool_6"))
        self.gridLayout_5.addWidget(self.lbl_pool_6, 2, 1, 1, 1)
        self.lbl_traded_capital_6 = QtGui.QLabel(self.grp_readjust)
        self.lbl_traded_capital_6.setObjectName(_fromUtf8("lbl_traded_capital_6"))
        self.gridLayout_5.addWidget(self.lbl_traded_capital_6, 2, 2, 1, 1)
        self.txt_risk_6 = QtGui.QLineEdit(self.grp_readjust)
        self.txt_risk_6.setEnabled(True)
        self.txt_risk_6.setAutoFillBackground(False)
        self.txt_risk_6.setStyleSheet(_fromUtf8("background : transparent;"))
        self.txt_risk_6.setFrame(True)
        self.txt_risk_6.setReadOnly(True)
        self.txt_risk_6.setObjectName(_fromUtf8("txt_risk_6"))
        self.gridLayout_5.addWidget(self.txt_risk_6, 3, 0, 1, 1)
        self.txt_price_6 = QtGui.QLineEdit(self.grp_readjust)
        self.txt_price_6.setEnabled(True)
        self.txt_price_6.setAutoFillBackground(False)
        self.txt_price_6.setStyleSheet(_fromUtf8("background : transparent;"))
        self.txt_price_6.setFrame(True)
        self.txt_price_6.setReadOnly(True)
        self.txt_price_6.setObjectName(_fromUtf8("txt_price_6"))
        self.gridLayout_5.addWidget(self.txt_price_6, 3, 5, 1, 1)
        self.lbl_risk_6 = QtGui.QLabel(self.grp_readjust)
        self.lbl_risk_6.setObjectName(_fromUtf8("lbl_risk_6"))
        self.gridLayout_5.addWidget(self.lbl_risk_6, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        self.verticalLayout_5.addWidget(self.grp_readjust)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.tab_main.addTab(self.tab, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.tab_main.addTab(self.tab_5, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tab_main.addTab(self.tab_3, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.tab_main.addTab(self.tab_6, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.grd_tables = QtGui.QGridLayout()
        self.grd_tables.setObjectName(_fromUtf8("grd_tables"))
        self.tbl_set_cash = QtGui.QTableWidget(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_set_cash.sizePolicy().hasHeightForWidth())
        self.tbl_set_cash.setSizePolicy(sizePolicy)
        self.tbl_set_cash.setAutoFillBackground(False)
        self.tbl_set_cash.setFrameShadow(QtGui.QFrame.Sunken)
        self.tbl_set_cash.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tbl_set_cash.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tbl_set_cash.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tbl_set_cash.setShowGrid(True)
        self.tbl_set_cash.setGridStyle(QtCore.Qt.NoPen)
        self.tbl_set_cash.setCornerButtonEnabled(False)
        self.tbl_set_cash.setObjectName(_fromUtf8("tbl_set_cash"))
        self.tbl_set_cash.setColumnCount(4)
        self.tbl_set_cash.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tbl_set_cash.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_set_cash.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_set_cash.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_set_cash.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_set_cash.setHorizontalHeaderItem(3, item)
        self.tbl_set_cash.horizontalHeader().setVisible(False)
        self.tbl_set_cash.verticalHeader().setVisible(False)
        self.tbl_set_cash.verticalHeader().setHighlightSections(True)
        self.grd_tables.addWidget(self.tbl_set_cash, 5, 1, 1, 1)
        self.tbl_division = QtGui.QTableWidget(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_division.sizePolicy().hasHeightForWidth())
        self.tbl_division.setSizePolicy(sizePolicy)
        self.tbl_division.setAutoFillBackground(False)
        self.tbl_division.setFrameShadow(QtGui.QFrame.Sunken)
        self.tbl_division.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tbl_division.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tbl_division.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tbl_division.setShowGrid(True)
        self.tbl_division.setGridStyle(QtCore.Qt.NoPen)
        self.tbl_division.setCornerButtonEnabled(False)
        self.tbl_division.setObjectName(_fromUtf8("tbl_division"))
        self.tbl_division.setColumnCount(4)
        self.tbl_division.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tbl_division.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_division.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_division.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_division.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_division.setHorizontalHeaderItem(3, item)
        self.tbl_division.horizontalHeader().setVisible(False)
        self.tbl_division.verticalHeader().setVisible(False)
        self.tbl_division.verticalHeader().setHighlightSections(True)
        self.grd_tables.addWidget(self.tbl_division, 1, 0, 1, 1)
        self.lbl_division = QtGui.QLabel(self.tab_4)
        self.lbl_division.setObjectName(_fromUtf8("lbl_division"))
        self.grd_tables.addWidget(self.lbl_division, 0, 0, 1, 1)
        self.lbl_set_investing = QtGui.QLabel(self.tab_4)
        self.lbl_set_investing.setObjectName(_fromUtf8("lbl_set_investing"))
        self.grd_tables.addWidget(self.lbl_set_investing, 4, 0, 1, 1)
        self.tbl_current_values = QtGui.QTableWidget(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_current_values.sizePolicy().hasHeightForWidth())
        self.tbl_current_values.setSizePolicy(sizePolicy)
        self.tbl_current_values.setAutoFillBackground(False)
        self.tbl_current_values.setFrameShadow(QtGui.QFrame.Sunken)
        self.tbl_current_values.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tbl_current_values.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tbl_current_values.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tbl_current_values.setShowGrid(True)
        self.tbl_current_values.setGridStyle(QtCore.Qt.NoPen)
        self.tbl_current_values.setCornerButtonEnabled(False)
        self.tbl_current_values.setObjectName(_fromUtf8("tbl_current_values"))
        self.tbl_current_values.setColumnCount(4)
        self.tbl_current_values.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tbl_current_values.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_current_values.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_current_values.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_current_values.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_current_values.setHorizontalHeaderItem(3, item)
        self.tbl_current_values.horizontalHeader().setVisible(False)
        self.tbl_current_values.verticalHeader().setVisible(False)
        self.tbl_current_values.verticalHeader().setHighlightSections(True)
        self.grd_tables.addWidget(self.tbl_current_values, 1, 1, 1, 1)
        self.lbl_current_values = QtGui.QLabel(self.tab_4)
        self.lbl_current_values.setObjectName(_fromUtf8("lbl_current_values"))
        self.grd_tables.addWidget(self.lbl_current_values, 0, 1, 1, 1)
        self.lbl_set_offense = QtGui.QLabel(self.tab_4)
        self.lbl_set_offense.setObjectName(_fromUtf8("lbl_set_offense"))
        self.grd_tables.addWidget(self.lbl_set_offense, 2, 1, 1, 1)
        self.lbl_set_defense = QtGui.QLabel(self.tab_4)
        self.lbl_set_defense.setObjectName(_fromUtf8("lbl_set_defense"))
        self.grd_tables.addWidget(self.lbl_set_defense, 2, 0, 1, 1)
        self.lbl_set_cash = QtGui.QLabel(self.tab_4)
        self.lbl_set_cash.setObjectName(_fromUtf8("lbl_set_cash"))
        self.grd_tables.addWidget(self.lbl_set_cash, 4, 1, 1, 1)
        self.tbl_set_investing = QtGui.QTableWidget(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_set_investing.sizePolicy().hasHeightForWidth())
        self.tbl_set_investing.setSizePolicy(sizePolicy)
        self.tbl_set_investing.setAutoFillBackground(False)
        self.tbl_set_investing.setFrameShadow(QtGui.QFrame.Sunken)
        self.tbl_set_investing.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tbl_set_investing.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tbl_set_investing.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tbl_set_investing.setShowGrid(True)
        self.tbl_set_investing.setGridStyle(QtCore.Qt.NoPen)
        self.tbl_set_investing.setCornerButtonEnabled(False)
        self.tbl_set_investing.setObjectName(_fromUtf8("tbl_set_investing"))
        self.tbl_set_investing.setColumnCount(4)
        self.tbl_set_investing.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tbl_set_investing.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_set_investing.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_set_investing.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_set_investing.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_set_investing.setHorizontalHeaderItem(3, item)
        self.tbl_set_investing.horizontalHeader().setVisible(False)
        self.tbl_set_investing.verticalHeader().setVisible(False)
        self.tbl_set_investing.verticalHeader().setHighlightSections(True)
        self.grd_tables.addWidget(self.tbl_set_investing, 5, 0, 1, 1)
        self.tbl_set_defense = QtGui.QTableWidget(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_set_defense.sizePolicy().hasHeightForWidth())
        self.tbl_set_defense.setSizePolicy(sizePolicy)
        self.tbl_set_defense.setAutoFillBackground(False)
        self.tbl_set_defense.setFrameShadow(QtGui.QFrame.Sunken)
        self.tbl_set_defense.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tbl_set_defense.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tbl_set_defense.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tbl_set_defense.setShowGrid(True)
        self.tbl_set_defense.setGridStyle(QtCore.Qt.NoPen)
        self.tbl_set_defense.setCornerButtonEnabled(False)
        self.tbl_set_defense.setObjectName(_fromUtf8("tbl_set_defense"))
        self.tbl_set_defense.setColumnCount(4)
        self.tbl_set_defense.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tbl_set_defense.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_set_defense.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_set_defense.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_set_defense.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_set_defense.setHorizontalHeaderItem(3, item)
        self.tbl_set_defense.horizontalHeader().setVisible(False)
        self.tbl_set_defense.verticalHeader().setVisible(False)
        self.tbl_set_defense.verticalHeader().setHighlightSections(True)
        self.grd_tables.addWidget(self.tbl_set_defense, 3, 0, 1, 1)
        self.tbl_set_offense = QtGui.QTableWidget(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_set_offense.sizePolicy().hasHeightForWidth())
        self.tbl_set_offense.setSizePolicy(sizePolicy)
        self.tbl_set_offense.setAutoFillBackground(False)
        self.tbl_set_offense.setFrameShadow(QtGui.QFrame.Sunken)
        self.tbl_set_offense.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tbl_set_offense.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tbl_set_offense.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tbl_set_offense.setShowGrid(True)
        self.tbl_set_offense.setGridStyle(QtCore.Qt.NoPen)
        self.tbl_set_offense.setCornerButtonEnabled(False)
        self.tbl_set_offense.setObjectName(_fromUtf8("tbl_set_offense"))
        self.tbl_set_offense.setColumnCount(4)
        self.tbl_set_offense.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tbl_set_offense.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_set_offense.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_set_offense.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_set_offense.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_set_offense.setHorizontalHeaderItem(3, item)
        self.tbl_set_offense.horizontalHeader().setVisible(False)
        self.tbl_set_offense.verticalHeader().setVisible(False)
        self.tbl_set_offense.verticalHeader().setHighlightSections(True)
        self.grd_tables.addWidget(self.tbl_set_offense, 3, 1, 1, 1)
        self.tbl_set_trading = QtGui.QTableWidget(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_set_trading.sizePolicy().hasHeightForWidth())
        self.tbl_set_trading.setSizePolicy(sizePolicy)
        self.tbl_set_trading.setAutoFillBackground(False)
        self.tbl_set_trading.setFrameShadow(QtGui.QFrame.Sunken)
        self.tbl_set_trading.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tbl_set_trading.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tbl_set_trading.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tbl_set_trading.setShowGrid(True)
        self.tbl_set_trading.setGridStyle(QtCore.Qt.NoPen)
        self.tbl_set_trading.setCornerButtonEnabled(False)
        self.tbl_set_trading.setObjectName(_fromUtf8("tbl_set_trading"))
        self.tbl_set_trading.setColumnCount(4)
        self.tbl_set_trading.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tbl_set_trading.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_set_trading.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_set_trading.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_set_trading.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tbl_set_trading.setHorizontalHeaderItem(3, item)
        self.tbl_set_trading.horizontalHeader().setVisible(False)
        self.tbl_set_trading.verticalHeader().setVisible(False)
        self.tbl_set_trading.verticalHeader().setHighlightSections(True)
        self.grd_tables.addWidget(self.tbl_set_trading, 5, 2, 1, 1)
        self.lbl_set_trading = QtGui.QLabel(self.tab_4)
        self.lbl_set_trading.setObjectName(_fromUtf8("lbl_set_trading"))
        self.grd_tables.addWidget(self.lbl_set_trading, 4, 2, 1, 1)
        self.verticalLayout_6.addLayout(self.grd_tables)
        self.tab_main.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tab_main)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab_main.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Emma", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_exit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_invest_buy.setTitle(QtGui.QApplication.translate("MainWindow", "Buy", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_commission.setText(QtGui.QApplication.translate("MainWindow", "Commission:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_pool.setText(QtGui.QApplication.translate("MainWindow", "Pool:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_price.setText(QtGui.QApplication.translate("MainWindow", "Price:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_traded_capital.setText(QtGui.QApplication.translate("MainWindow", "Traded capital:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_price_2.setText(QtGui.QApplication.translate("MainWindow", "Price:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_tax_2.setText(QtGui.QApplication.translate("MainWindow", "Tax:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_risk_2.setText(QtGui.QApplication.translate("MainWindow", "Risk:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_tax.setText(QtGui.QApplication.translate("MainWindow", "Tax:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_pool_2.setText(QtGui.QApplication.translate("MainWindow", "Pool:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_traded_capital_2.setText(QtGui.QApplication.translate("MainWindow", "Traded capital:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_risk.setText(QtGui.QApplication.translate("MainWindow", "Risk:", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_invest_sell.setTitle(QtGui.QApplication.translate("MainWindow", "Sell", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_commission_2.setText(QtGui.QApplication.translate("MainWindow", "Commission:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_pool_3.setText(QtGui.QApplication.translate("MainWindow", "Pool:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_price_3.setText(QtGui.QApplication.translate("MainWindow", "Price:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_traded_capital_3.setText(QtGui.QApplication.translate("MainWindow", "Traded capital:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_price_4.setText(QtGui.QApplication.translate("MainWindow", "Price:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_tax_3.setText(QtGui.QApplication.translate("MainWindow", "Tax:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_risk_3.setText(QtGui.QApplication.translate("MainWindow", "Risk:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_tax_4.setText(QtGui.QApplication.translate("MainWindow", "Tax:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_pool_4.setText(QtGui.QApplication.translate("MainWindow", "Pool:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_traded_capital_4.setText(QtGui.QApplication.translate("MainWindow", "Traded capital:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_risk_4.setText(QtGui.QApplication.translate("MainWindow", "Risk:", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_readjust.setTitle(QtGui.QApplication.translate("MainWindow", "Readjusting position for investments", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_commission_3.setText(QtGui.QApplication.translate("MainWindow", "Commission:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_pool_5.setText(QtGui.QApplication.translate("MainWindow", "Pool:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_price_5.setText(QtGui.QApplication.translate("MainWindow", "Price:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_traded_capital_5.setText(QtGui.QApplication.translate("MainWindow", "Traded capital:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_price_6.setText(QtGui.QApplication.translate("MainWindow", "Price:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_tax_5.setText(QtGui.QApplication.translate("MainWindow", "Tax:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_risk_5.setText(QtGui.QApplication.translate("MainWindow", "Risk:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_tax_6.setText(QtGui.QApplication.translate("MainWindow", "Tax:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_pool_6.setText(QtGui.QApplication.translate("MainWindow", "Pool:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_traded_capital_6.setText(QtGui.QApplication.translate("MainWindow", "Traded capital:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_risk_6.setText(QtGui.QApplication.translate("MainWindow", "Risk:", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_main.setTabText(self.tab_main.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Invest", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_main.setTabText(self.tab_main.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "Invest - position sizing", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_main.setTabText(self.tab_main.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Trade", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_main.setTabText(self.tab_main.indexOf(self.tab_6), QtGui.QApplication.translate("MainWindow", "Trade - position sizing", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_set_cash.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "shit", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_set_cash.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Total", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_set_cash.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Defense", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_set_cash.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Offense", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_set_cash.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "invest", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_division.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "shit", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_division.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Total", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_division.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Defense", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_division.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Offense", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_division.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "invest", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_division.setText(QtGui.QApplication.translate("MainWindow", "Calculate division", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_set_investing.setText(QtGui.QApplication.translate("MainWindow", "Needed pool/set investing", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_current_values.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "shit", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_current_values.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Total", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_current_values.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Defense", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_current_values.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Offense", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_current_values.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "invest", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_current_values.setText(QtGui.QApplication.translate("MainWindow", "Current values", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_set_offense.setText(QtGui.QApplication.translate("MainWindow", "Needed pool/set offense", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_set_defense.setText(QtGui.QApplication.translate("MainWindow", "Needed pool/set defense", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_set_cash.setText(QtGui.QApplication.translate("MainWindow", "Needed pool/set cash", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_set_investing.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "shit", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_set_investing.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Total", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_set_investing.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Defense", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_set_investing.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Offense", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_set_investing.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "invest", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_set_defense.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "shit", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_set_defense.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Total", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_set_defense.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Defense", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_set_defense.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Offense", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_set_defense.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "invest", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_set_offense.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "shit", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_set_offense.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Total", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_set_offense.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Defense", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_set_offense.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Offense", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_set_offense.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "invest", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_set_trading.verticalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "shit", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_set_trading.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Total", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_set_trading.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Defense", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_set_trading.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Offense", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tbl_set_trading.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "invest", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_set_trading.setText(QtGui.QApplication.translate("MainWindow", "Needed pool/set trading", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_main.setTabText(self.tab_main.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Profile", None, QtGui.QApplication.UnicodeUTF8))

