BEGIN;
truncate table T_FINANCE cascade;
truncate table T_ACCOUNT cascade;
truncate table T_COMMODITY cascade;
truncate table T_MARKET cascade;
truncate table T_TRADE cascade;
truncate table T_RATE cascade;
truncate table T_CURRENCY_EXCHANGE cascade;
truncate table T_CURRENCY cascade;
truncate table T_DRAWDOWN cascade;
truncate table T_COMMODITY_TYPE cascade;
truncate table T_CFD_GENERAL cascade;
COMMIT;
