BEGIN;
drop view V_EXPORT_LEDGER;
drop view V_ACCOUNT_NAME;
drop view V_REP_CHECK_TOTAL;
drop view V_FINANCE;
drop view V_ACCOUNT;
drop view V_COMMODITY;
drop view V_MARKET;
drop view V_TRADE;
drop view V_RATE;
drop view V_CURRENCY_EXCHANGE;
drop view V_CURRENCY;
drop view V_PARAMETER;
drop view V_POOL;
drop view V_EXPECTANCY;
drop view V_TRADE_JOURNAL;
drop view V_COMMODITY_TYPE;
drop view V_CFD_GENERAL;
drop view V_COMMODITY_INFO;
COMMIT;
