BEGIN;
drop table T_FINANCE cascade;
drop table T_ACCOUNT cascade;
drop table T_INVESTMENT cascade;
drop table T_COMMODITY cascade;
drop table T_MARKET cascade;
drop table T_MARGIN_TYPE cascade;
drop table T_MARGIN cascade;
drop table T_TRADE cascade;
drop table T_RATE cascade;
drop table T_CURRENCY_EXCHANGE cascade;
drop table T_CURRENCY cascade;
drop table T_FORMULA cascade;
drop table T_PARAMETER cascade;
drop table T_DRAWDOWN cascade;
drop table T_VERSION cascade;
drop table T_POOL cascade;
drop table T_BET cascade;
COMMIT;
