BEGIN;
truncate table T_MARKET cascade;
truncate table T_PRODUCT;
truncate table T_MARGIN_TYPE cascade;
truncate table T_MARGIN;
truncate table T_STOCK_CURRENT;
truncate table T_STOCK_NAME cascade;
truncate table T_STOCK;
truncate table T_FINANCE cascade;
truncate table T_OBJECT cascade;
drop table T_PRODUCT;
drop table T_MARGIN;
drop table T_MARGIN_TYPE;
drop table T_STOCK_CURRENT;
drop table T_STOCK;
drop table T_STOCK_NAME;
drop table T_MARKET;
drop table T_FINANCE;
drop table T_OBJECT;
COMMIT;
