BEGIN;
truncate table T_FINANCE cascade;
truncate table T_PRODUCT cascade;
truncate table T_OBJECT cascade;
truncate table T_ACCOUNT cascade;
truncate table T_STOCK cascade;
truncate table T_STOCK_NAME cascade;
truncate table T_MARKET cascade;
truncate table T_MARGIN cascade;
truncate table T_MARGIN_TYPE cascade;
truncate table T_STOCK_CURRENT;
drop table T_FINANCE cascade;
drop table T_PRODUCT cascade;
drop table T_OBJECT cascade;
drop table T_ACCOUNT cascade;
drop table T_STOCK cascade;
drop table T_STOCK_NAME cascade;
drop table T_MARKET cascade;
drop table T_MARGIN_TYPE cascade;
drop table T_MARGIN cascade;
drop table T_STOCK_CURRENT;
COMMIT;
